### ISSUE TITLE
La création d'une fiche de donnée devrait rediriger vers la page de détail

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#102]
A l'intersection entre #19 et #22 

**Problème**

Actuellement, lorsque l'on crée une fiche de données, l'application reste sur la page de contribution. Or on devrait pouvoir voir le résultat de la création.

**Solution proposée**

Rediriger automatiquement vers la page de détail

**Comment by DaFrenchFrog** [comment]
Cela peut être une bonne solution temporaire. A terme j'opterais plutôt pour une page de confirmation de contribution qui propose au choix de :
- consulter la page de détail
- Contribuer un nouveau jeu de données
- Retourner à l'accueil

Je vais vous faire une proposition qui va dans ce sens.
