### ISSUE TITLE
Indicateur "outil bêta"

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#105]
**Problème**
Pendant l'utilisation "MVP" de l'outil par certains usagers / ministères, il faut pouvoir signaler que le site n'est pas "finalisé", afin de clarifier les attentes.

**Solution proposée**

Dans la maquette je vois que @DaFrenchFrog a envisagé un bandeau supérieur disant par exemple "Ce site est en version bêta" (visible sur la page de login).

Maquette : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=690%3A22060

L'interaction semble être la suivante :

* A l'arrivée sur le site, le bandeau est visible en haut des pages
* Un bouton-croix permet de le fermer si on le souhaite, après quoi il n'apparaît plus au chargement du site

**Alternatives envisagées**

* Le bandeau doit-il effectivement pouvoir être désactivé ?
* Ajouter "Version bêta" ou similaire directement dans l'intitulé du site ? Dans le header, ou le footer...

**Comment by DaFrenchFrog** [comment]
Effectivement j'avais fait cette version pour ne pas vous obliger à modifier les composants par défaut et conserver ceux standards.

Mais si on peut améliorer ce point on pourrait avoir un bandeau permanent discret qui pourrait ressembler à ça : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=685%3A21042
