### ISSUE TITLE
La navigation client SvelteKit dysfonctionne sur une majorité de pages

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#110]
cc @magopian 

## Description du bug

Lors d'une navigation (clic sur un `<a>`), au lieu de ne changer que ce qui change dans la nouvelle page, SvelteKit semble généralement recharger l'ensemble de la page.

## Comportement attendu

La navigation client de SvelteKit est sensée modifier seulement le contenu du `<slot>` dans le `__layout.svelte`.

Ainsi, dans la console web par exemple, on devrait observer un _supplément_ de requêtes HTTP lors d'un changement de page.

## Comportement réel

La page est comme entièrement rechargée. La console web se vide puis l'ensemble des ressources sont à nouveau récupérées, le DSFR charge, etc.

La seule exception est le lien `/` dans le header.

## Pour reproduire

Lancer l'app avec `make serve`, puis :

- Accéder à http://localhost:3000 (page d'accueil)
- Ouvrir la console web
- Recharger la page (Ctrl+R), constater que la console se vide et se remplit avec l'ensemble des requêtes - C'est attendu
- Cliquer sur "Contribuer" dans la navbar
- Constater que la console se vide _aussi_ et l'ensemble des ressources sont récupérées :x:
- Toujours depuis la page "Contribuer", cliquer sur le header qui nous ramène sur la page d'accueil
- Constater que la console _ne se vide pas_, seules quelques requêtes HTTP sont faites :white_check_mark: 

On peut constater le même comportement avec `make build && make serve-dist`.

**Pistes de résolution**

TODO

**Comment by florimondmanca** [comment]
@magopian Hello, est-ce que tu as remarqué ceci aussi ?

**Comment by magopian** [comment]
Le lien "Rechercher" dans l'entête a le même soucis ...

**Comment by magopian** [comment]
Ok trouvé, le soucis c'est l'attribut `target="_self"`qu'il faut supprimer.
