### ISSUE TITLE
Noms de domaine

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#130]
Séparé de #67 

**Problème**

Actuellement nos 2 instances ("staging", "demo") sont accessibles uniquement par IP.

C'est convenable pour donner accès à l'outil "live" à des personnes (membres de l'équipe, usagers test, etc). Mais il faut anticiper que l'outil sera à terme accessible sur un domaine (par exemple catalogue.data.gouv.fr), et qu'il y aura du travail associé à cela.

**Solution proposée**

Associer dès maintenant un nom de domaine, de manière à intégrer ça aux outils d'infra (setup Ansible)

En l'occurrence, (staging|demo).catalogue.multi.coop

Ce nom de domaine sera lié au port 80, c'est-à-dire à Nginx. La configuration CORS de l'API ne devrait pas être modifiée : les requêtes continueront d'être faites depuis `localhost:3000` (le front). Le front ne devra pas non plus être modifié.

**Contexte**

C'est un prérequis à la configuration de TLS. En effet, même s'il est _possible_ de délivrer des certificats TLS pour une adresse IP, [LetsEncrypt](https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082?u=weppos) ne le permet pas. Or on passera par cet outil pour gérer les certificats.

**Comment by florimondmanca** [comment]
@johanricher Pourrais-tu faire la configuration DNS sur Scaleway pour chaque instance ?

Si je ne dis pas de bêtises il faut ajouter ces _records_ à `multi.coop` :

```
staging.catalogue 10800 IN A 51.159.187.137
demo.catalogue 10800 IN A 51.159.133.202 
```

**Comment by johanricher** [comment]
J'ai ajouté les enregistrements DNS pour le domaine `multi.coop` (Gandi).

```
dig staging.catalogue.multi.coop +short
51.159.187.137
```
```
dig demo.catalogue.multi.coop +short
51.159.133.202
```

**Comment by florimondmanca** [comment]
Top, ça a l'air opérationnel, merci :+1:
