### ISSUE TITLE
ETQ admin je peux supprimer une fiche de données afin d'éviter les données obsolètes

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#151]
J'ouvre ce ticket pour discuter d'une fonctionnalité "suppression de fiche de données".

En effet pour la phase de demo/beta/dev il peut être pertinent de pouvoir simplement supprimer une fiche de données d'exemple/test qui n'aurait plus rien à faire là, par ex pour une prochaine demo.

Par contre, en vue d'un usage plus sérieux, ça déterre plusieurs questions

- Usage : un bouton ? placé où ? confirmation ?
- Permissions : qui peut supprimer une fiche de données : admin uniquement ? tout usager ? seulement au sein de son propre catalogue (cf #122) ?
- Traçabilité des données : doit-on garder la trace de la fiche de données en base = _soft delete_ ?
- Etc

Qu'en pensez-vous @johanricher @DaFrenchFrog ?

**Comment by DaFrenchFrog** [comment]
Excellente question. 
Pour l'instant je n'ai pas de réponse affirmative mais j'espère que les tests nous éclairerons sur le sujet.

**Comment by johanricher** [comment]
De mon point de vue ce serait une fonctionnalité uniquement accessible aux utilisateurs responsables (https://jailbreak.gitlab.io/investigation-catalogue/synthese.html#/19/4), afin d'éviter les suppressions abusives ou erreurs de manipulation par n'importe qui et sans non plus ajouter un process de validation de suppression.

D'un point de vue UX, ça pourrait être un bouton qui ne s'affiche que quand on est dans la vue édition d'une fiche (et pas directement en vue lecture).

Par ailleurs, il faudra aborder ces sujets dans le cadre du chantier "multi-catalogue", mais mon point de vue c'est que seuls les membres d'une organisation peuvent éditer leur propre catalogue (et dans l'idée où 1 organisation = 1 catalogue, ce qui peut être remis en question mais qui rendrait encore plus complexes ces mécaniques liées à "qui peut faire quoi").

**Comment by DaFrenchFrog** [comment]
Sur ce point je suis d'accord. Seul un admin de son catalogue peut supprimer une fiche de donnée.
Et pour les réutilisateurs on pourrait aussi envisager une suggestion de modification qui consisterait à supprimer la fiche, et l'admin n'aurait qu'à valider la suppression pour qu'elle soit effective.

**Comment by florimondmanca** [comment]
Il semble donc qu'on ait une nouvelle dépendance sur #20... :)

**Comment by florimondmanca** [comment]
@DaFrenchFrog J'ai avancé sur ce ticket avec une implem dans #171. Comment vois-tu ça niveau design ? À ce stade ces outils "admin" sont "pour nous" donc j'ai fait une mise en page ad-hoc. J'imagine qu'à terme il faudrait entrer ça dans la maquette ?
