### ISSUE TITLE
ETQ user je vois un menu latéral à coté du formulaire de création de fiche de donnée

### ISSUE THREAD

**Issue by Volubyl** [etalab/catalogage-donnees#156]
##  Description du besoin

Lorsque je remplis le formulaire, ETQ user j'ai besoin de me situer dans ce formulaire et de pouvoir revenir/aller rapidement à une partie de ce formulaire. Pour ce faire, j'aimerais disposer d'un menu.

Lien Epic : #125 

Maquette :  https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=843%3A22535
Lien vers le DSFR : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/258998801/Menu+lat+ral+-+Side+menu

## Règles métiers

// To Do

## Analyse Technique

// To Do

**Comment by florimondmanca** [comment]
@Volubyl Est-ce que cette issue a été résolue par #208 aussi ?
