### ISSUE TITLE
Implémenter les métadonnées d'une fiche jeu de données

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#166]
## Contexte

* Il faut distinguer métadonnées de la fiche jeu de données (= informations qui ont trait à la fiche elle-même, les contributions dessus, etc.) et métadonnées du jeu de données (= informations qui ont trait à un jeu de données = schéma du catalogue cf. #125).
* Exemples :
  *` last_updated_at `: date de modif du jeu de données, ou de la fiche elle-même ?
  * `creator` : faut-il enregistrer qui a contribué une fiche de données ?
  * `visibility` (open, shared, internal), `closed_reason`, etc... : il faut que les utilisateurs comprennent sans ambiguité si ce sont les données ou la fiche qui sont en open data
* Même une _séparation technique_ serait souhaitable : pour qu'en tant que dev on puisse facilement savoir à quoi correspond chaque champ, par ex dans un retour d'API.

## Champs à implémenter

* `created_at`

## Design

Maquette fiche jeu de données : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=843%3A22296

## Critères d'acceptation

Implémenter seulement les champs nécessaires pour le cas d'usage du MC.

## Tâches

- [x] Lister champs métadonnées fiche
  - `created_at` (existe déjà)
- [x] Implémenter champs métadonnées fiche :  https://github.com/etalab/catalogage-donnees/pull/189

**Comment by johanricher** [comment]
Quelle est la source de vérité pour déterminer la liste des champs des métadonnées d'une fiche jeu de données ? (pour l'instant seulement ceux dont on a besoin pour le cas d'usage MC) 
Est-ce que les maquettes suffisent pour savoir ce qu'il faut implémenter ou il faut détailler davantage ? @DaFrenchFrog @florimondmanca @Volubyl

**Comment by DaFrenchFrog** [comment]
Si je me place du point de vue utilisateur, il n'y a pour l'instant pas eu de besoin remonté de faire cette distinction côté front donc pour l'instant cette problématique reste technique. Je laisse donc les spécialiste s'exprimer sur le sujet.

**Comment by johanricher** [comment]
Ma question peut être reformulée de la sorte : quelles sont les informations dont on a besoin et qui ont traits aux métadonnées d'une fiche de jeu de données ?
- contributeurs ?
- date de création ?
- date de dernière mise à jour ?
- visibilité ?

La première utilisation de ces métadonnées est évidemment de les afficher dans l'UI (i.e. si elles ne sont pas utiles aux utilisateurs, peut-être qu'on a tout simplement pas besoin d'avoir ces métadonnées, de les créer, collecter, stocker) mais ça peut être des usages plus indirects.

Exemple : si on veut pouvoir ordonner dans l'UI du catalogue les jeux de données par date de dernière mise à jour (on n'utilisera pas la date de dernière mise à jour du jeu de données lui-même car souvent on ne l'aura pas ou elle ne sera pas fiable) auquel cas on devra avoir cette métadonnée

C'est la liste de ces champs qu'il faut fixer ici.

**Comment by florimondmanca** [comment]
Je vais essayer de répondre en éclairant diverses pistes. Ce sont des notes rapides, j'espère être clair.

TL;PL (_trop long; pas lu_) : Si Romain semble dire qu'il n'y a pas encore de besoin identifié, je pense qu'on pourra en rester à [l'état des lieux](#etat-des-lieux) de ce qui existe, et éventuellement la clarification technique [Dataset vs Datasheet](#dataset-vs-datasheet). À ce stade la signification de `visibility` (que j'avais introduite pour modéliser les options "Open data ou non ? Visible par d'autres organisations ou non ?") me semble à clarifier avant de décider s'il s'agit d'une métadonnée de fiche ou d'un champ de la fiche (et donc, une métadonnée sur le jeu de données - _on s'y perd_...).

## Etat des lieux

Actuellement on a les métadonnées de fiche suivantes :

- `created_at` - Date de création de la fiche de données
- `search_tsv` - Index de recherche sur titre et description

## Dataset vs Datasheet

On a évoqué jeudi dernier une "séparation technique" de cette séparation logique entre métadonnées _du jeu de données_ (la fiche elle-même) et métadonnées _à propos de la fiche_.

Actuellement, tout est stocké dans une entité `Dataset`. On y trouve donc par exemple `title` (titre _du jeu de données_) et `created_at` (date de création _de la fiche_).

On pourrait donc procéder à la séparation suivante : `Dataset` vs `Datasheet` (ou `DatasetMeta` ? disons `Datasheet` pour l'exposé).

- Cette séparation apporte essentiellement de la clarté.
- Même principe qu'une séparation entre `UserAccount` (compte utilisateur administratif : email, password) et `UserProfile` (profil utilisateur : pseudo, préférences...).
- Plus tard, je ne pense pas que les connecteurs remettent en cause cette modélisation. Même "importé" via OpenDataSoft ou autre, un jeu de données (Dataset) devra toujours être décrit et donc avoir une fiche (Datasheet).

Modèle logique : `Dataset 1:1 --- 1:1 Datasheet`. Lecture : un jeu de données a exactement une fiche correspondante.

Modèle physique (non-formalisé) :

- `Dataset` - Informations décrivant _le jeu de données_
  - title
  - description
  - formats
  - tags
  - ...
- `Datasheet` - Informations décrivant _la fiche de données_
  - dataset_id
  - created_by
  - ...

## Nouvelles métadonnées

Je vais ici essayer de réfléchir "fonctionnellement". En effet il semble inutile de stocker des données dont on ne ferait rien.

La priorité est donc de questionner les différents besoins, ce qui rejoint aussi une démarche d'écoconception : que stocker, qu'afficher, pour quoi faire ? Là-dessus on semble en phase et c'est heureux.

### Ouverture

- `visibility` - "open", "shared", "internal" - Définit l'ouverture de la fiche _au sein de l'outil de Catalogage_. Il y a une ambigüité latente je trouve : il faut qu'il soit clair qu'on parle ici de la fiche elle-même, et non pas du statut Open Data ou non du jeu de données. Si `visibility = open`, cela veut-il dire que la fiche est accessible publiquement ? Depuis quel endroit sur l'outil (pas encore de "site public") ? Si non, le jeu de données est marqué comme "open data" avec par exemple un lien DataGouv, mais dans ce cas n'est-ce pas une information _sur le jeu de données lui-même_, qui se recoupe en partie avec la licence (qui accompagne nécessairement un jeu de données en Open Data, non ?). @DaFrenchFrog @johanricher Je me fais peut-être trop de noeuds au cerveau mais je serais intéressé de votre avis.

### Historique des modifications

Ici je vais explorer l'idée d'un historique, car les infos 'date de dernière mise à jour' et 'contributeurs' cités par @johanricher nous y amènent assez vite.

#### Version minimale

En version minimale, on afficherait la dernière modification, soit :

- `updated_at` - Date de dernière modification de la fiche ("Dernière mise à jour le <updated_at>")

### Version "liste de contributeurs"

Dans cette approche, on stockerait la liste des personnes ayant contribué à la fiche au cours du temps -- sans stocker le détail des modifications.

Techniquement, on aurait donc la relation logique de contribution suivante : `User 0:n --(contributes_to)-- 1:n Datasheet`. Lecture : un utilisateur peut contribuer à des fiches de données, et une fiche de données a au moins un contributeur (la personne qui a initialement créé la fiche, puis les personnes qui ont successivement mis à jour la fiche).

La relation physique (tables en BDD) serait : `Dataset -> DatasetContributor <- User`. L'enregistrement d'un contributeur se ferait en ajoutant un couple (dataset_id, user_id) à `DatasetContributor`.

Niveau UI, ça permettrait de faire qqc comme la section "Contributors" de GitHub sur l'accueil d'un repo -- mais pas plus, car on ne stockerait pas le contenu des modifications.

La question centrale restant : pour quoi faire, pour répondre à quel besoin ? Pour la contribution comme la contribution, ne serait-ce pas une information "doublon" avec les contacts ? À mon humble avis, si un besoin émerge, ce sera celui d'une simple traçabilité.

#### Version "full Wikipedia"

Ici on passerait en mode Wikipedia : [history](https://en.wikipedia.org/w/index.php?title=The_Cathedral_and_the_Bazaar&action=history) + [compare](https://en.wikipedia.org/w/index.php?title=The_Cathedral_and_the_Bazaar&type=revision&diff=1078764615&oldid=1065899578)). ll faudrait :

- `updated_by` - Le dernier `User`  contribué à la fiche au cours de sa vie (d'abord création initiale, puis modifications successives)
- `Revision` - Un modèle de données qui contient une fiche de données entre deux modifications.
  - S'inspirer de [django-simple-history](https://github.com/jazzband/django-simple-history) ?
  - Le modèle logique serait : `Dataset 0:n--1:1 DatasetRevision 1/ 1:1---0:n User` (lecture : une révision est liée à une fiche de données et un auteur)
  - Contenu :
    - `id` - Identifiant
    - `title`, `description`, etc... - Snapshots des champs de `Dataset` que l'on voudrait historiciser
    - `revision_date` - Date de modification
    - `revision_change_reason` - Description courte de la modification
    - `revision_author` - `User` à l'origine de la modification
  - Contenu : une révision a un `id`, un `diff` ( qui permet de comparer deux états de la fiche, et donc de générer un diff (c'est le même système que git, l'historique wikipedia, migrations de BDD, etc). En mode minimal, on peut y adjoindre une simple `description` des changements, sans stockage de diff (les versions précédentes de la fiche, qu'on pourrait reconstituer en remontant les diffs, ne seraient donc plus accessibles une fois la ).

Il va sans dire que cette fonctionnalité en version "complète" serait un gros morceau.

**Comment by johanricher** [comment]
Merci pour ton commentaire Florimond. Il contient beaucoup de choses, j'espère que je ne loupe rien.

D'abord je reformulerais la différence entre les métadonnées d'un jeu de données et celle d'une fiche d'une autre façon, afin de peut-être donner un autre angle d'éclairage sur ces notions. Les métadonnées d'une fiche sont strictement propres à notre outil, elles ne sont utiles qu'à nous, utilisables que par nous, et pour nos besoins spécifiques. En revanche les métadonnées d'un jeu de données sont génériques, elles peuvent être utiles et utilisées par d'autres et même chargées et affichées dans d'autres outils interopérables avec notre schéma catalogue (basé sur DCAT-AP) comme par exemple les portails data.gouv.fr et OpenDataSoft. Inversement, nous pourrions moissonner ces catalogues publics pour intégrer les métadonnées des jeux de données qu'ils contiennent dans un catalogue de notre outil.

## Sur l' "ouverture" 

En gros tes remarques et questions me semblent non seulement pertinentes mais toutes valides. En détaillant un peu plus :

Le besoin sera à un moment de savoir par quels utilisateurs peut être lue une fiche d'un catalogue. On avait initialement parlé de 3 niveaux d'accès pour une fiche donnée dans une instance de l'outil :
1. Membres de l'organisation à laquelle appartient le catalogue (accès "interne")
2. Membres d'autres organisations (accès "inter-ministériel"). Etant donné que le multi-catalogue n'est pas encore implémenté, ce niveau n'a pour l'instant pas de sens.
3. Tout le monde (accès "public" sans authentification nécessaire). Etant donné (en plus de la remarque au point 2) que l'outil est pour l'instant accessible uniquement en étant authentifié, que ce niveau de "catalogue public" a vocation à être sur data.gouv.fr et qu'on ne sait pas comment on va gérer ça, ce niveau n'a pour l'instant pas de sens.

:warning: A ne pas confondre en effet avec la notion d' "ouverture" attachée au jeu de données lui-même, qui correspond en fait à la notion de licence open data (ou son absence) et qui a son propre champ dans le schéma du catalogue.

> Quid d'un jeu de données "partagé" (entre organisations), qui n'est donc pas encore en Open Data ?

Dans un tel cas, le champ "licence" peut contenir la valeur "None" ou "Aucune". Sinon on peut aussi rendre ce champ optionnel ([il est "recommandé" dans la spec DCAT-AP](file:///home/johan/Downloads/dcat-ap_final_v1.00_0.html#Distribution%20-%20licence)).

## Sur l'historique des contributions et des contributeurs

On en aura besoin tôt ou tard c'est certain. Si ça ne rajoute pas trop de complexité (au chantier du mois) de faire en sorte de collecter ces métadonnées dès maintenant, j'y suis favorable. Sinon, je préfère qu'on s'y attaque plus tard.

> La relation physique (tables en BDD) serait : `Dataset -> DatasetContributor <- User`

On parle ici de contributions à une fiche donc c'est plutôt des notions de "Datasheet" et "DatasheetContributor" qu'il s'agirait selon moi d'utiliser ici.

Le reste de la description technique que tu fais me paraît correct.

> La question centrale restant : pour quoi faire, pour répondre à quel besoin ? Pour la contribution comme la contribution, ne serait-ce pas une information "doublon" avec les contacts ? À mon humble avis, si un besoin émerge, ce sera celui d'une simple traçabilité.

C'est vrai que sans l'historique des contributions elles-mêmes (stocker chaque version des métadonnée d'un jeu de données à chaque nouvelle contribution), la liste des contributeurs à un moindre intérêt. Cependant il faut considérer que les personnes qui contribuent à une fiche et les personnes qui sont mises comme "contacts" sur un jeu de données ne sont pas forcément les mêmes. Les premières peuvent être par exemple des personnes en responsabilité qui contribuent beaucoup au catalogue et à la description de beaucoup de jeu de données, les deuxièmes peuvent être par exemple des agents métiers qui ont une connaissance importante sur le jeu de données voire qui l'ont même produit, sans pour autant contribuer directement au catalogue (idéalement il le faudrait mais ça sera pas toujours le cas).

Aller vers une fonctionnalité similaire à celle de Wikipedia (savoir qui a modifié une fiche et quand., pouvoir annuler une contribution, revenir en arrière) serait un en garde-fou essentiel pour rendre efficace la modération à posteriori. J'ai conscience que c'est une fonctionnalité qui nécessiterait un gros chantier, et entrainerait une augmentation substantielle du volume de métadonnées stockées (puisqu'il faudrait 

Pour l'instant garder seulement la liste des contributions et leur timestamp est suffisant

**Comment by florimondmanca** [comment]
> A ne pas confondre en effet avec la notion d' "ouverture" attachée au jeu de données lui-même, qui correspond en fait à la notion de licence open data (ou son absence) et qui a son propre champ dans le schéma du catalogue.

En effet, donc on a bien l'ouverture du jeu de données et la "visibilité" (portée ? - _scope_) de la fiche au sein de l'outil.

J'ai vu que @DaFrenchFrog avait mis à jour la partie "Ouverture" de la maquette. Il ne reste plus qu'un switch "Disponible en open data" et un champ texte conditionnel pour une URL. En revanche l'idée initiale d'une "visibilité" (open data / restreint / ...) était bien présente sur la maquette intiale et persiste sur la page "Validation" présente sur la maquette à ce jour.

En bref, si jamais une telle "visibilité" est ajoutée à l'outil plus tard (ça a l'air probable), je conclus donc que c'est une information qui rentrera dans les métadonnées de fiche, car elle est spécifique à notre outil.

> Pour l'instant garder seulement la liste des contributions et leur timestamp est suffisant

Qu'entend-on par "contributions", donc ? La description technique de `Revision` que j'ai faite te semble correspondre ? Si oui, je suis un petit peu confus car alors le "est suffisant" se rapporterait à la version maximaliste de la feature, qui permettrait de faire toutes ces fonctionnalités de retour arrière, annulation, etc. :sweat_smile: Si non, est-ce que ce serait plutôt qqc du type : qui a fait une modification et quand, avec une description libre (mais obligatoire) du changement effectué ?

**Comment by DaFrenchFrog** [comment]
> J'ai vu que @DaFrenchFrog avait mis à jour la partie "Ouverture" de la maquette. Il ne reste plus qu'un switch "Disponible en open data" et un champ texte conditionnel pour une URL. En revanche l'idée initiale d'une "visibilité" (open data / restreint / ...) était bien présente sur la maquette intiale et persiste sur la page "Validation" présente sur la maquette à ce jour.

Attention il n'a pas disparu c'est juste que c'est la version cochée qui est sur la maquette. Mais si tu testes le prototype [ici](https://www.figma.com/proto/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?page-id=431%3A11368&node-id=843%3A22535&viewport=373%2C48%2C0.75&scaling=min-zoom&starting-point-node-id=690%3A22060&show-proto-sidebar=1) ou que tu regarde le composant dans [la librairie](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=763%3A25740) tu auras accès à toutes les étapes. J'en profite aussi pour dire que cette section va évoluer en terme de design car les utilisateur ne voient/comprennent pas bien le switch. Donc je vais passer à un modèle plus direct où l'on pose une question oui/non. Cela ne change rien au niveau du principe mais c'est juste plus clair.

**Comment by johanricher** [comment]
> Qu'entend-on par "contributions", donc ? La description technique de Revision que j'ai faite te semble correspondre ? 

On est bien d'accord : on veut tendre vers une fonctionnalité "à la Wikipedia" maximaliste, mais je sais même pas si ça sera une fonctionnalité au lancement ou plus tard donc on parle de quelque chose de lointain et hypothétique. Il s'agira le moment venu de définir ça plus en détail du point de vue utilisateur. Mon "pour l'instant" revient (je crois) à ta première fonctionnalité "liste de contributeurs" : on ne garde en base qu'un timestamp de chaque contribution et le user associé ("datasheet contributor"). Je pense que le simple fait de pouvoir afficher cet historique sera utile comme fonctionnalité minimaliste, mais à définir plus tard.

**Comment by johanricher** [comment]
@DaFrenchFrog Après avoir regardé une nouvelle fois les maquettes de contribution sur la partie ouverture je pense qu'elles font perdurer la confusion entre 1) l'ouverture de la fiche et 2) l'ouverture du jeu de données. La maquette pose des questions qui vont plutôt servir à répondre au point 1) or comme je disais ci-dessus seul l'accès "interne" est possible donc on ne peut pas implémenter ça pour l'instant. Pour le point 2) si le jeu de données est déjà "disponible en open data" ça veut dire que dans les faits il est sur un portail open data donc un simple lien répond à la question. En revanche s'il n'a pas été publié ce n'est pas forcément qu'il y a une raison qui s'y oppose ! dans 90 % des cas c'est juste qu'ils ne l'ont pas encore fait, même si la loi les y oblige..

**Comment by DaFrenchFrog** [comment]
Je n'ai pas eu de remontées jusqu'ici sur cette confusion mais dans la mesure où les testeurs étaient plutôt experts il est possible qu'il y en ait une...

On peut peut-être séparer en deux parties avec un titre comme "Accès aux données" et "Visibilité de cette fiche de données". Les termes accès et visibilité permettent de bien faire la distinction entre ce qui est "là-bas" et dont on souhaite obtenir "l'accès", et ce qui est "dans l'outil" et qui peut être visible ou pas. Qu'en pensez-vous ?

**Comment by DaFrenchFrog** [comment]
Autre option changer les questions pour avoir :
- Les données sont-elles accessibles en open data ?
Et ensuite
- Cette fiche de données est-elle visible par les autres organisations ?

**Comment by johanricher** [comment]
Ok pour "Visibilité (ou Partage ?) de cette fiche : interne / inter-ministériel / public". Et utiliser les termes "open" et "open data" uniquement pour parler du jeu de données.

> Les données sont-elles accessibles en open data ?

Je reformulerais en "Les données sont elles ouvertes ?" (si oui quel est lien pour y accéder etc.)

> Cette fiche de données est-elle visible par les autres organisations ?

Il faudrait reformuler en partant du principe que le partage est en accès public par défaut et permettre à l'utilisateur de définir un accès plus restreint si ça se vérifier par ses réponses à des questions. Mais encore une fois je pense qu'il est trop tôt pour designer ça car 1. le multi-catalogue n'est pas encore implémenté, donc le niveau "inter-ministériel" n'a pour l'instant pas de sens. et 2 l'outil est accessible uniquement en étant authentifié, le niveau "public" a vocation à être sur data.gouv.fr et on ne sait pas comment on va gérer ça.

**Comment by johanricher** [comment]
> une table séparée que j'ai appelée catalog_record plutôt que datasheet. (Si je ne m'abuse c'est le vocabulaire DCAT-AP et je trouve ça plus facile à distinguer visuellement que dataset / datasheet.)

[En effet, bien vu !](https://w3c.github.io/dxwg/dcat/#Class:Catalog_Record) (pour le contexte : [DCAT-AP](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe) est un "profil" une extension à DCAT)

De manière générale ça peut être pas mal de reprendre les noms des propriétés / champs dans DCAT, quand elles existent et qu'elles ne sont pas contradictoires avec nos besoins et méthodes.

**Comment by florimondmanca** [comment]
Suite à réunion du 21/04 :

- La notion de "visibilité" (intra/inter/"public") est abandonnée pour le cas d'usage MC car présuppose du multi-catalogue
- La question ouverture est : "Ce jeu de données est-il publié en open data ?"

Pour le cas d'usage MC, ce qui est à faire :

- [ ] #189  Séparation technique des métadonnées de fiche : notion de "_catalog record_"
  - Liste des champs _pour le cas d'usage MC_ :
    - `created_at` (existe déjà, à déplacer)

**Comment by florimondmanca** [comment]
La séparation technique #189 a été faite, je vais fermer ce ticket pour l'instant, étant entendu qu'on pourra suite au cas d'usage MC regarder les évolutions futures évoquées dans les messages précédents.
