### ISSUE TITLE
Déployer une instance pour le ministère de la Culture

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#168]
## Contexte

Dans le cadre du [jalon du 5 mai](https://github.com/etalab/catalogage-donnees/milestone/2), nous déployons une instance de l'outil de catalogage qui contiendra un seul catalogue : celui du ministère de la Culture (MC).

C'est sur cette instance qu'on importera le catalogue du MC (#169) et qu'on créera les comptes utilisateurs du MC (#170).

Cette instance permettra de mener les tests avec le MC. Elle ne sera pas forcément mise à jour en continu (contrairement à l'instance staging) afin d'éviter de casser le catalogue (si par exemple le schéma ou l'API évoluent). Ce n'est pas pour autant une instance de production. Pas de garantie de service (les données peuvent être perdues).

Cette instance pourrait servir par la suite aux tests avec d'autres parties prenantes (#122).

## Tâches

- [x] Provisionner un serveur (même que staging et demo)
   - Manip sur Scaleway, cf https://github.com/etalab/catalogage-donnees/issues/67#issuecomment-1064246923
   - Enregistrement DNS : `catalogue.multi.coop`
   - Sortie : `51.159.147.207` / `catalogue.multi.coop`
- [ ] Déployer l'instance #214
  - Ajouter un environnement `sandbox` à `ops/ansible/environments`, en mettant à jour la doc `docs/ops.md`
  - `make provision env=sandbox` - Installer les langages, outils, services, etc.
  - _Ne pas lancer d'initdata_ (pas besoin car on créera les comptes et importera le catalogue MC plus tard)
  - `make deploy env=sandbox` - Déployer l'outil
  - Sortie : un déploiement accessible sur `https://catalogue.multi.coop`, catalogue vide

**Comment by florimondmanca** [comment]
@johanricher Juste qq questions pour clarifier. 

* J'ai l'impression que cette instance séparée est un moyen de pallier à l'absence de multi-org à ce stade, on est d'accord ?
* J'envisage donc qu'on crée une instance physique séparée (une autre VM avec sa propre version du code) et en utilisant une nouvelle DB sur l'instance Postgres, comme on l'a fait pour demo #67. Ça te semble approprié ?
* On la nommerait qqc comme `culturegouvfr.catalogue.multi.coop` ?

**Comment by johanricher** [comment]
> J'ai l'impression que cette instance séparée est un moyen de pallier à l'absence de multi-org à ce stade, on est d'accord ?

Pas forcément, en principe rien ne s'oppose à ce qu'on utilise l'instance démo pour faire nos tests avec le MC (importer leur catalogue, créer des utilisateurs, les laisser utiliser l'outil...) mais je crains qu'on ne pourra plus mettre à jour en continu cette instance au risque de perturber le déroulement des tests (une mise à jour de l'outil déployée sur l'instance qui casserait le catalogue suite à un changement du schéma par exemple). Si on peut éviter ce problème-là sans déployer une instance dédiée, pourquoi pas ?

Avoir une instance "démo" qui correspond toujours à la dernière version de l'outil, tel que mergé sur `master`, et avec des fixtures, données factices etc. comme on l'a aujourd'hui me paraît avoir une utilité en soi. Mais peut-être que l'instance "staging" peut servir à ça ?

> J'envisage donc qu'on crée une instance physique séparée (une autre VM avec sa propre version du code) et en utilisant une nouvelle DB sur l'instance Postgres, comme on l'a fait pour demo. a te semble approprié ?

Si avoir une 3ème instance est la solution oui ça serait les même modalités que précédemment.

> On la nommerait qqc comme `culturegouvfr.catalogue.multi.coop` ?

Tel que je le vois, cette instance aura vocation à voir d'autres organisations que le MC dès que la gestion multi-catalogue sera prête à être testée donc je lui donnerais dès maintenant un nom lié à son usage plus générique (faire des tests avec des vrais utilisateurs). J'ai du mal à l'appeler "production" mais c'est peut-être à ça que ça correspond ?

**Comment by florimondmanca** [comment]
@johanricher Ça me paraît OK ! Je suis d'accord pour une 3e instance. En effet ça pourrait servir de prod en réalité... Et donc s'appeler `catalogue.multi.coop`. Quoiqu'il en soit, la 1ère étape est donc d'obtenir une nouvelle VM sur Scaleway. J'ai mis le lien des specs qu'on avait utilisé en description, je le remets ici : https://github.com/etalab/catalogage-donnees/issues/67#issuecomment-1064246923
