### ISSUE TITLE
Reprise des champ(s) contact

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#179]
Refs #125 

Comme cette feature est déjà développée je me permet de créer un ticket à part. A voir si vous voulez le jardiner ou pas :)

[Sur la maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=843%3A22535) il est indiqué qu'il faut au moins un email de service mais je pense que le mieux serait d'imposer simplement un email, qu'il soit de service ou personnel.

Même si la bonne pratique est d'avoir un email de service le risque est que s'il n'existe pas d'email de service (ou que l'utilisateur ne le connait pas), la personne saisira un email personnel dans celui réservé au service pour pouvoir passer cette étape...

**Comment by DaFrenchFrog** [comment]
Attention @johanricher je ne suis pas pour n'avoir qu'un seul champ. :) 
Je pense qu'il faut garder les deux mais que la validation se fasse sur le remplissage de l'un OU l'autre.

**Comment by johanricher** [comment]
Comme tu le dis toi-même la notion d'email de service n'est pas systématique à l'intérieur des organisations comme le ministère de la culture ou, quand il existe, il n'est pas toujours connu. Et encore une fois ça ne répondrait à aucun problème utilisateur en l'état actuel des choses. De toute évidence ça n'a aucun sens de garder un champ qui ne sera pas utile.
Donc, d'après tes recherches, s'il faut garder un 2ème champ "contact"' que devrait-il contenir et à quel problème utilisateur cela devrait répondre (en particulier au MC) ?

**Comment by DaFrenchFrog** [comment]
Dans le fichier excel du MC il y a cette distinction donc autant conserver les deux champs.
Et même s'il n'y a pas toujours d'email de service la bonne pratique est d'en avoir un donc je pense qu'il faut le laisser pour promouvoir cette pratique et encourager son utilisation.

**Comment by johanricher** [comment]
Après vérification dans le catalogue MC une énorme partie de ces emails que le MC appelle "boîte fonctionnelle" sont des emails du service open data et donc pas le service où est produit le jeu de données référencé. Ca montre bien que demander des infos dont les contributeurs ne disposent pas conduit à ce que le champ sera mal rempli et sera inutile voire même entrainera des confusions (l'utilisateur croit contacter le service producteur et ce n'est pas le cas). Je pense qu'on doit être très vigilant à amont par rapport aux anti patterns de ce genre.

**Comment by DaFrenchFrog** [comment]
Si certains ne connaissent pas l'existence d'un mail de service il n'y a pas de raison de pénaliser ceux qui le connaissent. Et si on est d'accord que l'utilisation d'un email de service est une bonne pratique alors il faut la soutenir et pas la masquer à mon sens. Par ailleurs ce problème de "mauvais remplissage" n'est pas résolu en n'ayant qu'un seul champ. 

Mais peut-être ce cette divergence de point de vue est liée à une interprétation différente de la prise de contact :
Pour moi lorsqu'un réutilisateur prend contact. L'email est envoyé à tous les comptes qui ont été enregistrés (qu'ils soient de service ou personnel), et dans le contenu on insère en plus du message les références qui permettent aux destinataires de remonter jusqu'à la fiche. Ainsi tout le monde est au courant.

Pour aller plus loin on pourrait même donner la possibilité à l'admin d'être inclu dans toutes les prises de contact qui se feront sur son catalogue.

Concernant le choix de l'email de service ce n'est pas à nous de juger si il doit être un email open data ou un service plus granulaire. Chaque organisation fait comme elle veut mais notre recommandation est d'avoir un email qui ne dépend pas de "personnes".

Dis-moi ce que tu en penses.

**Comment by johanricher** [comment]
> l'utilisation d'un email de service est une bonne pratique

Je constate juste qu'à ce stade, d'après les éléments dont on dispose, ce n'est même pas une pratique répandue.

> Si certains ne connaissent pas l'existence d'un mail de service il n'y a pas de raison de pénaliser ceux qui le connaissent

On constate ici qu'une personne responsable au MC, qui a passé beaucoup de temps sur son catalogue, n'a pas été en mesure de renseigner un "email de service" pour la majorité des services. Je le prends comme un signe que ces emails n'existent pas ou qu'ils sont peu connus. 

Dans tous les cas on constate que le champ "boîte fonctionnelle" ne correspond pas à notre définition du champ "contact service" puisqu'il contient des adresses emails qui ne sont pas liées au service où sont produites les données. Donc, si l'on garde ce champ, que doit-on faire dans le cadre de #169 ? supprimer les emails qui n'appartiennent pas à un service producteur et donc laisser ces champs vides sur une majorité de fiches ? Est-ce que la personne responsable du catalogue remettra les emails incorrects ? Sinon qui pourra renseigner les emails corrects ?

> Pour moi lorsqu'un réutilisateur prend contact l'email est envoyé à tous les comptes (...)

Ton commentaire m'a fait reprendre la maquette ce qui m'a aidé à me mettre en conditions réelle, et en prenant le temps de la réflexion je pense qu'il faudrait revoir le bouton "Contacter le producteur" ça il me semble que ça prête à confusion :
* Il peut y avoir plusieurs personnes contact
* ETQ utilisateur j'ai envie de savoir qui sont les personnes (pour l'instant : voir leur adresse email) avant de cliquer sur le bouton
* ETQ utilisateur j'ai envie de contacter une personne en particulier (cliquer sur son adresse email) et pas forcément toutes.

Dans une navigation sur le web, cliquer sur une adresse email affichée sur une page ouvre le client email par défaut, ce qui permet d'écrire et envoyer l'email. Un scénario différent où un clic remplirait le champ destinataire du client mail avec plusieurs contacts (s'il y en a) ne me paraît pas être un comportement auquel s'attendrait un utilisateur. En tout cas ça mérite une exploration ! 

> Concernant le choix de l'email de service il me semble que ce n'est pas à nous de juger si il doit être un email open data ou un service plus métier. Chaque organisation fait comme elle veut mais notre recommandation est d'avoir un email qui ne dépend pas de "personnes".

Je pense qu'on mélange dans cette discussion (1) la problématique du ou des champs contact : "à quoi ils servent et comment ils vont être utilisés ?" qui est l'objet de ce ticket, avec (2) la problématique "qu'est-ce qui est visible et par qui ?" qui sera notamment exploré dans le cadre du multi-catalogue et dont on n'a pas besoin de s'occuper avant : pour l'instant tous les membres de l'organisation connectés (et seulement eux) peuvent voir tout le catalogue.

Il faut cependant être clair sur la définition qu'on donne à la notion de "service", ce que j'ai fait dans le cadre des travaux sur schéma du catalogue : "Service producteur du jeu de données au sein de l'organisation". C'est celle sur laquelle on s'est accordés avec les parties prenantes au cours de [l'atelier de juillet dernier](https://lite.framacalc.org/9p8z-schema_catalogue_donnees) et qui figurait dans différents documents notamment [le schéma (brouillon)](url) publié en septembre.

**Comment by florimondmanca** [comment]
Synthèse après réunion du 28/04

- Rendre email personnel obligatoire (au moins 1) - actuellement pas de contrainte
- Rendre email de service optionnel - actuellement obligatoire
- Reprendre le wording de la maquette
