### ISSUE TITLE
ETQ utilisateur je peux procéder aux réglages de l'outil / mon compte

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#184]
J'ouvre ce ticket car dans la maquette et dans l'état actuel de l'outil, nous avons un bouton "Réglages" dans le header, à côté de "Déconnexion".

Actuellement ce bouton ne fait rien.

Le sujet est : quel effet doit avoir ce bouton ?

- Ouverture d'une page "Profil utilisateur" ? (Modification prénom, nom, email...) Quelle allure aurait-elle ?
- Autre ?

Et : quelle priorité / horizon pour une telle fonctionnalité ? Cas d'usage MC, "bêta plus tard" (plus probable) ?

(Je note aussi que pour l'instant on ne stocke ni prénom ni nom dans `User`, seulement l'email.)

**Comment by johanricher** [comment]
A priori la modification du compte utilisateur (prénom, nom, email) n'est pas un must have pour le jalon du 5/05 (embarquement d'utilisateurs du MC dans une instance dédiée à des fins de tests). Néanmoins si c'est identifié comme un besoin à l'avenir il faudra ouvrir un ticket dédié, écrit "En tant que...", et on verra si une page de "préférences" (personnelles) est la bonne façon d'y répondre. Il y aura j'imagine aussi en parallèle le besoin de rendre modifiable par des utilisateurs de type "responsables" (admin) d'autres réglages au niveau de l'instance ("paramètres"). Ce sont donc des choses à aborder distinctement avec comme tout premier point de départ à chaque fois la définition d'un problème à résoudre d'un point de vue utilisateur, et qu'on pourra prioriser séparément suites aux tests à venir.

**Comment by johanricher** [comment]
De manière générale je suis plutôt favorable à ce qu'on n'implémente pas des choses qui apparaissent dans les maquettes mais qui ne correspondent à aucune fonctionnalité existante et qui n'ont pas encore été décrits dans des tickets (et donc avec des réponses au genre de questions que tu poses ici @florimondmanca). Je propose donc d'enlever le bouton "Règlages", "Mon espace", les infos concernant la "qualité", etc.

**Comment by florimondmanca** [comment]
> Je propose donc d'enlever le bouton "Règlages", "Mon espace", les infos concernant la "qualité", etc.

:+1: On était d'ailleurs arrivé à ce genre de conclusion avec @Volubyl.

**Comment by florimondmanca** [comment]
Je ferme en faveur de #190
