### ISSUE TITLE
Enlever les boutons et éléments graphiques sans fonctionnalité

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#190]
Tiré de #184

> De manière générale je suis plutôt favorable à ce qu'on n'implémente pas des choses qui apparaissent dans les maquettes mais qui ne correspondent pas à des fonctionnalités ou données existantes et qui n'ont pas encore été décrits dans des tickets.
>
> Je propose donc d'enlever le bouton "Règlages", "Mon espace", les infos concernant la "qualité", etc.

Recensement de telles "éléments d'interface fantôme" :

- Bouton "Réglages"
- "Couverture temporelle"
- "Qualité"

(À corréler à l'état de la maquette "Cas d'usage MC")

- [x] Maquette mise à jour
- [x] Outil développé mis à jour

**Comment by DaFrenchFrog** [comment]
Done.

**Comment by florimondmanca** [comment]
@DaFrenchFrog Fait dans la maquette, mais pas dans le dev, non ? :smile:

**Comment by DaFrenchFrog** [comment]
Pardon je pensais que ça ne concernait que le design ! 😅
