### ISSUE TITLE
ETQ contributeur, je peux renseigner un lien vers la page open data

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#191]
Refs #125 

Cf maquette : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1482%3A46092

Il manque les champs :

- `url` - "Lien vers les données"

NB : on ne stocke pas de champ `is_published`, car à ce stade cette information se déduit de `url` : `is_published := url is not None`. Le front devra probablement gérer une variable pour le oui/non, mais n'enverra que `url` au backend.

**Comment by florimondmanca** [comment]
@DaFrenchFrog Hello,

Sur la maquette ce n'est pas précisé, mais est-ce que l'utilisateur est obligé de renseigner un lien vers les données si le jeu de données est indiqué comme publié en open data ?

(Je demande car ça conditionne un peu l'implémentation de mon côté. Si ce n'est pas le cas, alors on peut se retrouver avec un jeu de données "publié" mais sans URL, ce qui m'oblige à créer un champ à part `is_published` en BDD. Sinon, je peux l'inférer de la présence ou non d'une URL.)

**Comment by johanricher** [comment]
open data = par définition qu'il y a une page publique qui permet de télécharger le jeu de données (et que celui-ci est associé à une licence open data mais c'est un autre champ du schéma qu'on ne renseigne pas pour l'instant).

Le formulaire aurait pu se content de demander l'URL de cette page plutôt que de poser 2 questions pour que le contributeur renseigne l'URL mais ce n'est que mon avis.

**Comment by florimondmanca** [comment]
@johanricher Oui, ce qui irait donc dans le sens de rendre l'URL obligatoire si on répond "oui" à la question "est-ce publié en open data?".

**Comment by florimondmanca** [comment]
Pour l'instant dans #197 j'ai implémenté un seul champ "Page open data" (wording incertain) qui ressemble à ceci :

![Screenshot 2022-04-25 at 17-36-10 Catalogue](https://user-images.githubusercontent.com/15911462/165123415-320709f2-e3f6-4772-bd2f-2e7a6ca58fce.png) (24 kB)

**Comment by DaFrenchFrog** [comment]
J'avais maquetté le cas oui/non sur le figma : 
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/25462034/165247626-426ad355-7342-4e64-85cb-7faa231ba19e.png">

Mais je suis ok avec les commentaires donc on peut laisser ainsi pour le cas d'usage MC je vais modifier la maquette dans ce sens. Lorsque l'on s'intéressera aux suites du cas "non" on pourra implémenter la question de nouveau.
