### ISSUE TITLE
Créer comptes utilisateurs pour le Ministère de la Culture

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#220]
## TODO

* [x] @DaFrenchFrog fournit une liste de 7 users non admin (leur adresse pro) sur Nextcloud
* [x] @florimondmanca crée les comptes utilisateurs

**Comment by florimondmanca** [comment]
Les comptes ont été créés et communiqués à @DaFrenchFrog via le Nextcloud.

@DaFrenchFrog propose de communiquer leurs identifiants aux utilisateurs lors des entretiens.
