### ISSUE TITLE
ETQ utilisateur je peux voir le statut open data d'une fiche de jeu de données

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#222]
# Design
### Carte jeu de données 
- [ ] Ajouter un badge sur la carte ([maquette ici](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=431%3A17444))

### Fiche jeu de données
La maquette et ses deux statuts possible (open data ou restreint) est ici : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1578%3A62167

# Conditions d'acceptation

- [ ] L'état du composant dépend de la présence ou non d'un lien. S'il y a un lien, on affiche l'option "open data", s'il n'y en a pas on affiche l'option "restreint"

- [ ] Dans le cas open data  le lien est clicable et ouvre un nouvel onglet

**Comment by Volubyl** [comment]
@DaFrenchFrog j'ai une petite interrogation par rapport aux badges.

Dans le DSFR, j'ai l'impression que les badges n'autorisent qu'un nombre limité d'icone et qu'ils déconseillent d'utiliser une icone "custom"

Voir doc ici : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/851869737/Badges et la partie "ne pas faire"

Bref, si on est rigoriste par rapport au DSFR on ne pourrait pas utiliser de badge (mon intepretation est elle juste ?)

Sauf que là c'est la deuxième fois que l'on est bloqué par le DSFR et je ne sais quelle attitude adoptée.

Pour le coup, ma propal serait de outrepasser le DSFR et faire un composant html avec du CSS qui n'utilise pas le DSFR.

Genre : 

```
<a class="badge" href="#" > 
   <span class="fr-fi-fixxx"/> 
   open data 
 </a>
 
 <style>
 
 .badge {
   background-color : var(<la variable de couleur qui va bien>)
   ....
 }
</style>
```
@florimondmanca  tu en penses quoi ?

**Comment by florimondmanca** [comment]
D'après le Slack DSFR, le composant badge est assez jeune, il a été ajouté avec la version 1.3.0 du DSFR publiée en janvier 2022. Ça explique peut-être pourquoi il a ces limites.

Ou alors c'est par conception : la page de documentation insiste lourdement sur le fait qu'un badge est pensé pour refléter un "état" ou un "statut". Par ailleurs un encart décourage spécifiquement d'utiliser des icônes :

> À ne pas faire - Utiliser une icône dans un badge standard

On lit aussi:

> Pour catégoriser, classer, organiser des contenus à l'aide de mots-clés, utiliser plutôt le composant [Tag](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/310706305).

-> Faudrait-il imaginer de plutôt utiliser un `Tag` ?

**Comment by florimondmanca** [comment]
@Volubyl Si l'icône n'est pas disponible par défaut il faut l'ajouter manuellement à notre fonte d'icônes custom. J'avais déjà dû le faire pour certaines ici donc on a un outil Python tout fait. J'ai écrit une doc ici : https://github.com/etalab/catalogage-donnees/blob/master/docs/fr/outils.md#icônes-supplémentaires

**Comment by DaFrenchFrog** [comment]
Je vais poser la question mais je suis assez convaincu que l'on peut faire les choses comme maquettées. Chez nous le statut d'ouverture est un sujet majeur et je ne vois pas de raison qui empêcherait l'utilisation d'un badge.

@Volubyl pour récupérer les icone tu peux aller [ici](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=431%3A17444) et à partir de là le plus simple je pense est de faire clic droit :
<img width="490" alt="image" src="https://user-images.githubusercontent.com/25462034/167567093-4d9986ad-9215-48b9-99ad-6e8c53975bfd.png">
Sinon tu as la fonction export en bas à droite dans l'onglet design. Dis-moi si c'est ok. 

Sinon pour tous les pictos autres que les pictos open data (qui sont custom), la source est la librairie Remix icons qui est utilisée par le DSFR : https://remixicon.com/

**Comment by DaFrenchFrog** [comment]
@Volubyl @florimondmanca Après avoir vu avec les équipes DSFR les badges avec icônes sont "réservés".

Du coup j'ai modifié les cartes. 
- On reprend le même modèle d'item que pour les formats et couverture territoriale
- Selon le statut on change l'icône afférente

**Comment by florimondmanca** [comment]
Lien vers la doc Fontello : https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images Il y a des contraintes sur le format du SVG de l'icône

**Comment by Volubyl** [comment]
@DaFrenchFrog c'est ok pour le SVG ! Merci!

Tu pourrais me filer celui pour l'autre icone ?

**Comment by DaFrenchFrog** [comment]
Top. Voici :
`<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17.657 5.65685L12.0001 0L6.34325 5.65685L7.75746 7.07107L11.0001 3.82843L11.0001 16.6569H13.0001L13.0001 3.82843L16.2427 7.07107L17.657 5.65685Z" fill="#000091"/>
<path d="M4.9289 4.58579C1.02365 8.49104 1.02365 14.8227 4.9289 18.7279C8.83414 22.6332 15.1658 22.6332 19.071 18.7279C22.9763 14.8227 22.9763 8.49104 19.071 4.58579L18.3639 3.87869L19.7781 2.46447L20.4852 3.17158C25.1715 7.85787 25.1715 15.4559 20.4852 20.1421C15.799 24.8284 8.20097 24.8284 3.51468 20.1421C-1.17161 15.4558 -1.17161 7.85787 3.51468 3.17158L4.22179 2.46447L5.636 3.87869L4.9289 4.58579Z" fill="#000091"/>
</svg>
`

**Comment by DaFrenchFrog** [comment]
@Volubyl avec un seul path :
`<svg width="24" height="22" viewBox="0 0 24 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M4.92893 2.12132C1.02369 6.02656 1.02369 12.3582 4.92893 16.2635C6.62692 17.9614 8.78362 18.9212 11.0001 19.1426L11.0001 4.36395L7.7575 7.6066L6.34329 6.19238L12.0001 0.535528L17.657 6.19238L16.2428 7.6066L13.0001 4.36395L13.0001 19.1426C15.2166 18.9211 17.3731 17.9614 19.0711 16.2635C22.9763 12.3582 22.9763 6.02656 19.0711 2.12132L18.364 1.41421L19.7782 0L20.4853 0.707107C25.1716 5.3934 25.1716 12.9914 20.4853 17.6777C15.799 22.364 8.20101 22.364 3.51472 17.6777C-1.17157 12.9914 -1.17157 5.3934 3.51472 0.707107L4.22183 0L5.63604 1.41421L4.92893 2.12132Z" fill="#000091"/>
</svg>
`
