### ISSUE TITLE
Mettre à jour le DSFR : 1.3.1 -> 1.5.1

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#227]
cc @Volubyl 

Actuellement on utilise `@gouv/dsfr@1.3.1`, version en vigueur au lancement du projet (janvier 2022).

La version la plus récente est la 1.5.1, publiée le 26 avril 2022 : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/999489723/Version+1.5

Dans une optique de gestion de dette technique, on devrait mettre le DSFR à jour

# Changements cassants

Les changements suivants sont mis en avant, ils peuvent être cassants - voir les changelogs pour les détails

### Icônes

Changelog:

> ✨  Ajouts d’icônes supplémentaires et classement par catégories (celles de RemixIcon).
> 
> :warning:  Déplacement des utilitaires d’icônes dans un dossier utility. 
> Les classes d’icônes peuvent maintenant être importés depuis 
> dist/utility/utility.css et dist/utility/icons/icons.css, ou plus spécifiquement par catégorie, ex: dist/utility/icons/icons-system/icons-system.css.
> Les icônes du dsfr sont préfixées par “fr--”, contrairement à celles de remixIcon.
> Les icônes ne sont plus utilisées sous la forme d'une font-icon mais en mask-image: url() avec le chemin de l’icône.

Changements déduits :

* Les icônes se font par un masque plutôt que par une fonte. Cela devrait permettre de simplifier l'intégration d'icônes custom (plus besoin de Fontello).

```css
/* @gouvfr/dsfr/dist/utility/icons/icons.css */
.fr-icon-ancient-gate-fill::before {
  -webkit-mask-image: url("../../icons/buildings/ancient-gate-fill.svg") !important;
  mask-image: url("../../icons/buildings/ancient-gate-fill.svg") !important;
}
```

* Changement de nom dans les classes : `fr-fi-*` devient `fr-icon-*`. Mais `fr-fi-*` est toujours supporté donc on pourra faire la modif après l'upgrade.

> utiliser des icônes en utilisant directement la classe CSS associée, reprenant le nom de l’icône SVG, précédée du préfixe fr-icon ou  **fr-fi (déprécié)**. 
> Exemple :  .fr-icon-error-fill, .fr-fi-account-fill.
> (Source : [doc mise à jour](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331396/Ic+nes+-+Icons#Pour-les-d%C3%A9veloppeurs)) 

## v1.4

* Classes utilitaires :

🛠️ Correction de nom de classes utilitaires : 
     :warning:fr-display-sm devient fr-display--sm (idem pour md, lg, xl)
     :warning:fr-text--xx-bold devient fr-text--heavy
     :warning:fr-displayed-sm devient fr-unhidden-sm (idem pour md, lg, xl)

 :warning: Les utilitaires fr-displayed-(sm,md,lg) , fr-display-(sm,md,lg) , fr-text--xx-bold sont dépréciés. 
Utilisez maintenant respectivement : fr-unhidden-(sm,md,lg) , fr-display--(sm,md,lg) , fr-text--heavy

* Header :

:warning: Changement de la structure html :

Le bouton de fermeture des modals de search et menu en mobile deviennent des boutons tertiaires sans contour.  Les classes fr-link fr-link--close sont dépréciées et remplacées par fr-btn fr-btn--close.

Le groupe de lien d’accès rapide, devient un groupe de bouton :

     fr-links-group est déprécié et est remplacé par fr-btns-group

    fr-link est déprécié et est remplacé par fr-btn

* Navigation :

:warning: Changement de la structure html :

Les classes fr-link fr-link--close sont dépréciées et remplacées par fr-btn fr-btn--close.

Dans l’exemple du ‘leader’ du mega-menu  : fr-displayed-lg est déprécié et devient fr-unhidden-lg.

* Pied de page

:warning: Logo opérateur et logos partenaire: la taille est désormais gérée sur les image de manière inline, et non plus forcée dans la feuille de style: à adapter selon vos besoin!

# Nettoyages possibles

Des ajouts et modifications dans le DSFR pourraient nous inspirer les changements suivants :

* Indicateur bêta (cf #105) : le DSFR propose désormais un snippet avec un badge `BETA` affiché à côté du nom du site : [Déclinaison avec badge bêta](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222789846/En-t+te+-+Header#D%C3%A9clinaison-avec-badge-%22B%C3%AAta%22)
* Supprimer le `fr-fi-calendar-line` dans le datepicker du champ "Dernière date de mise à jour" :
    > Input
    > 🛠️ Correction input type date, la classe fr-fi-calendar-line n'est plus nécéssaire
* Icônes : la v1.4 a ajouté diverses icônes - cf [changelog](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/978354177/Version+1.4#Code) -> vérifier si certaines correspondent à des icônes de notre fonte custom, et les en retirer le cas échéant

**Comment by florimondmanca** [comment]
@DaFrenchFrog Pour se synchroniser, quelle version utilises-tu côté maquettes ? Je vais faire la màj du DSFR côté dev aujourd'hui.

**Comment by DaFrenchFrog** [comment]
@florimondmanca Je suis sur la 1.5.0.
