### ISSUE TITLE
Avoir un champ "searchable-select"

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#236]
# Contexte
Avoir un champ Select dans lequel on peut sélectionner plusieurs options serait utile dans deux cas pour l'instant :
- Sur la page de contribution/édition pour la sélection de mot-clés
- Sur la recherche avancée pour la sélection des formats

A noter que ce type de champ pourrait être intéressant pour le choix du format dans la page de contribution/édition également car le nombre d'item pourrait être amené à évoluer également.

# Comportement attendu
Le multi select est un champ select classique qui contient en tant qu'items des composants checkbox taille SM.
Dans la plupart des contextes d'utilisation ce champ pourra être associé à un ajout suppression de tags mais ce n'est pas une obligation.

# Maquettes & prototype
- [Maquettes](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1933%3A34132)

- [Prototype](https://www.figma.com/proto/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?page-id=431%3A17442&node-id=1933%3A34247&viewport=2446%2C-1487%2C0.96&scaling=min-zoom&starting-point-node-id=1933%3A34247)

**Comment by Volubyl** [comment]
@DaFrenchFrog @johanricher est-ce que cette issue est tjs d'actualité ? Si oui, je peux commencer à la dev ?

**Comment by DaFrenchFrog** [comment]
Pour moi elle est toujours d'actualité mais on peut la découper en deux parties :
- Avoir un select avec un champ de recherche mais sans les checkbox (c'est-à-dire pas de multi-select)
- donner la possibilité de sélectionner plusieurs item à la fois (mais si on implémente cette feature alors il faudra trouver un moyen de les afficher

**Comment by Volubyl** [comment]
@DaFrenchFrog j'ai fait un prototype ici : https://svelte.dev/repl/498d50fdf6ff466da7a8bc6d492bc128?version=3.48.0

Est-ce que c'est qqch comme ça à quoi tu pensais pour le 

>Avoir un select avec un champ de recherche mais sans les checkbox (c'est-à-dire pas de multi-select) ?
