### ISSUE TITLE
Modification des wordings du formulaire de contribution/modification

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#240]
### Page

- [ ] Le texte "Modifier le jeu de donnée (sic)" est affiché même si je suis dans la page de contribution => Si je suis dans la création du jeu de données, le texte doit être "Créer une fiche de jeu de données". Si je modifie une fiche déjà existante le texte doit être "Modifier une fiche de jeu de données".

### Informations générale
- [ ] Titre du jeu de la donnée : dans la description ajouter à la fin "Pour des raisons pratiques il est limité à 100 caractères."
- [ ] Nom du jeu de la donnée :  remplacer par "Nom du jeu de données"
- [ ] Nom du jeu de la donnée : Limiter le nombre de caractères de ce champ à 100
- [ ] Couverture territoriale : mette "territoires d'Outre-mer inclus"
- [ ] Mettre "Service producteur" au lieu de "Service producteur de la donnée"
- [ ] Ajouter en description "Service producteur du jeu de données au sein de l'organisation."

### Champ mot-clés
- [ ]  Mot-clés : Remplacer "Sélectionner un mot-clé" par par "Ajouter un mot-clé"
- [ ]  Mot-clés : Lorsqu'un mot-clé est ajouté, remettre le wording d'origine (et non le mot-clé sélectionné)

### Mise à jour
- [ ] Texte intro : mettre un "s" jeu de donnée_s_
- [ ]  Fréquence de mise à jour : il n'y a pas de "e" à _plusieurs_

### Bouton de publication
- [ ] Si nous sommes sur la page de modification mettre "Enregistrer les modifications"

**Comment by florimondmanca** [comment]
@DaFrenchFrog J'avais seulement une question sur ce changement:

> Nom du jeu de la donnée : Limiter le nombre de caractères de ce champ à 100

* Quelle est la motivation derrière ce changement ?
* Doit-on empêcher de rentrer plus de 100 caractères (comportement par défaut de `<input maxlength="100">`) ?
* Ou autoriser de rentrer plus de 100 caractères, mais afficher un message d'erreur empêchant de soumettre les modifications ?

**Comment by DaFrenchFrog** [comment]
@florimondmanca J'ai prévu cette limitation pour ne pas avoir un nom trop long, qui serait contre-productif. Effectivement la deuxième option parait la plus adaptée, et chose que à laquelle je n'avais pas pensé est de prévenir de la limitation. Le wording doit donc également changer.

Je le rajoute dans le ticket.

**Comment by florimondmanca** [comment]
@DaFrenchFrog #240 est prête à prévisualiser sur staging : https://staging.catalogue.multi.coop

J'avais un questionnement par rapport à cette limitation à 100 caractères. La voie choisie est de ne faire qu'une limitation côté front (dans la DB, les titres de + de 100 caractères existants continueront d'exister). Mais on a actuellement 

Mais que sont sensés devenir les titres qui dépassent cette limite ?

Par exemple sur sandbox il y a celui ci (173 caractères) :

> Dépenses et recettes culturelles des établissements publics de coopération intercommunale (EPCI) à fiscalité propre comportant au moins une commune de 3500 habitants ou plus

Il semble adéquat. Mais à la prochaine modification, l'utilisateur buttera sur la limite de 100 caractères, ne permettant d'écrire que (je tronque pour l'exemple) :

> Dépenses et recettes culturelles des établissements publics de coopération intercommunale (EPCI) à f

Devrait-on plutôt envisager une limite de 200 caractères ? 250 ?

**Comment by florimondmanca** [comment]
J'ai mergé la plupart des modifications envisagées, sauf la limitation du nb de caractères dans le titre, j'ai ouverte cette issue pour finaliser la discussion : #261

**Comment by DaFrenchFrog** [comment]
Ok je répond sur l'autre alors.
