### ISSUE TITLE
Cas d'usage MC : temps de latence sur le retour à la page d'accueil

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#242]
## Description du bug

Lorsque l'on ouvre la page de contribution et qu'on la referme, il se passe plusieurs secondes après le clic sans que rien ne se passe avant de revenir à la page. Le problème est que la "moulinette" qui s'affiche généralement dans ces cas-là ne s'affiche pas et on a l'impression que le site est bloqué et/ou que notre clic n'a pas été pris en compte.

## Pour reproduire
- Aller sur le cas d'usage MC
- Afficher la page d'accueil (la liste des jeux de données)
- Aller sur une fiche de données (ou toute autre page)
- Revenir sur l'accueil (via le back navigateur ou un clic sur le logo principal)

## Pistes de résolution

Option 1 : le spinner doit s'affiche au niveau de l'onglet du navigateur
Option 2 : afficher un spinner custom (détails à discuter en équipe)

**Comment by florimondmanca** [comment]
@DaFrenchFrog Il faut d'abord que je déploie la pagination sur la sandbox. Le ralentissement que tu observes est très probablement lié à ces très longues requêtes. Normalement on l'observe aussi en arrivant sur le site.

**Comment by florimondmanca** [comment]
@DaFrenchFrog J'ai redéployé https://catalogue.multi.coop qui comporte désormais la pagination à 50 items. J'ai l'impression que le délai s'est largement réduit. À mon sens il reste encore trop grand pour un bête chargement de 50 items de la DB, mais j'ai ma petite idée d'où ça peut venir.

Toujours est-il, est-ce que ça réduit le besoin d'un spinner ?

**Comment by DaFrenchFrog** [comment]
Je confirme. Le temps est largement réduit et on ne se pose plus de question. Je ferme ce ticket.

**Comment by florimondmanca** [comment]
"For the record", j'ai fait un peu de profiling / mesurage des requêtes SQL en local, grâce à [fastapi-debug-toolbar](https://github.com/mongkok/fastapi-debug-toolbar)

J'obtiens ces ordres de grandeur sur une requête d'exemple à l'endpoint d'API `GET /datasets/` :

* Temps de réponse : 44 ms, dont 23 ms CPU côté serveur
  * Sur sandbox, on oscille entre 400 et 600 ms, soit x10 au moins
* SQL: 7 requêtes en environ 10 ms
  * SELECT user - 0.6 ms x 2 (dupliquée)
  * SELECT count(*) _(calcul nb datasets)_ - 1.0 ms
  * SELECT ... FROM datasets ... _(récup datasets)_ - 2.6 ms
  * SELECT ... FROM dataset JOIN dataset_tag JOIN tag _(récup tags)_ - 1.7 ms
  * SELECT ... FROM dataset JOIN catalog_record _(récup métadonnées de fiche)_ - 1.8 ms
  * SELECT ... FROM dataset JOIN dataset_dataformat JOIN dataformat _(récup formats)_ - 1.3 ms

Ce qui me rassure, c'est qu'on n'a pas de [N+1 query problem](https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping) : on fait 5 requêtes indépendamment du nb de datasets. C'était attendu de mon côté mais ça le confirme.

Ce qui m'interpelle par contre c'est le x10 en durée entre localhost et la sandbox. Je ne m'attendais pas à un tel décalage dû à un "vrai réseau" (DB et serveur chez chez Scaleway vs en localhost).

À l'occasion je referai le même exercice en activant la toolbar sur la sandbox directement...

**Comment by DaFrenchFrog** [comment]
OK top. Si tu penses que c'est utile tu peux rouvrir le ticket.
