### ISSUE TITLE
Modifications front sur la fiche de jeu de données

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#243]
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/25462034/168862864-f5af5b69-0b2b-402d-a5c0-b81108ff9494.png">

- [ ] Au dessus du titre : en attendant d'implémenter la donnée "organisation, mettre en dur "Ministère de la culture" et non le nom du producteur de la donnée #253
- [x] Donner une largeur maximale à la colonne de gauche pour qu'un nom long ne prenne pas la place réservée au descriptif. -> Inclus dans #226

**Comment by johanricher** [comment]
Surtout à la place de "Producteur" il faut mettre "Service producteur". @DaFrenchFrog est-ce que tu peux mettre à jour les maquettes pour qu'elles soient alignées avec le schéma ? (on a convenu que [la source de vérité est ce tableau](https://lite.framacalc.org/0c5a3v0z3t-9th0)).

**Comment by DaFrenchFrog** [comment]
> Surtout à la place de "Producteur" il faut mettre "Service" (le champ a pour description "Service producteur du jeu de données au sein de l'organisation."). @DaFrenchFrog est-ce que tu peux mettre à jour les maquettes pour qu'elles soient alignées avec le schéma ? (on a convenu que [la source de vérité est ce tableau](https://lite.framacalc.org/0c5a3v0z3t-9th0)).

@johanricher J'ai modifié doc excel et maquette pour mettre "Service producteur" car si dans le formulaire "service" seul fonctionne grâce au descriptif, c'est moins le cas sur la fiche.
