### ISSUE TITLE
ETQ contributeur je ne peux rentrer un titre plus long que 100 caractères afin de faciliter la lisibilité

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#261]
Extrait de #240

J'ouvre cette issue pour affiner encore un peu l'idée de limiter à N (100 ?) caractères la longueur du `title`.

Ça pose un certain nombre de questions :

- Quelle est la formulation "ETQ" de ce changement (cf titre incomplet de cette issue) ? Quel besoin utilisateur cherche-t-on à satisfaire ?
- Limitation "douce" (uniquement dans le front), "semi-dure" (contrainte dans l'API) ou "dure" (contrainte dans la DB) ? En toute rigueur, la contrainte devrait être au plus proche du domaine modélisé, et donc inscrite aussi dans la DB (qui n'est qu'une implémentation particulière de stockage de ce domaine). Alors, la migration du schéma amènerait la question (1).
- (1) Que faire des titres existants qui dépasseraient les N caractères (cf instance MC) ?

## Contexte

Formulation initiale dans #240 :

> Nom du jeu de la donnée : Limiter le nombre de caractères de ce champ à 100

Discussion dans #240 :

> @DaFrenchFrog a écrit :
> @florimondmanca J'ai prévu cette limitation pour ne pas avoir un nom trop long, qui serait contre-productif. Effectivement la deuxième option parait la plus adaptée, et chose que à laquelle je n'avais pas pensé est de prévenir de la limitation. Le wording doit donc également changer.

> @florimondmanca a écrit :
> J'avais un questionnement par rapport à cette limitation à 100 caractères. La voie choisie est de ne faire qu'une limitation côté front (dans la DB, les titres de + de 100 caractères existants continueront d'exister).
> Mais cela veut dire que pour les titres existants qui dépassent 100 caractères, l'utilisateur se verra dans l'obligation (forcée par la machine) de réduire le titre à moins de 100 caractères lors de la prochaine modification (sinon le formulaire ne sera pas accepté).
> Je pense que c'est problématique, que ça repose la question quelle utilité (vu de l'utilisateur) a cette limite.
> Par exemple sur sandbox il y a celui-ci (173 caractères) :
> > Dépenses et recettes culturelles des établissements publics de coopération intercommunale (EPCI) à fiscalité propre comportant au moins une commune de 3500 habitants ou plus
>
> Il semble adéquat. Mais à la prochaine modification, l'utilisateur buttera sur la limite de 100 caractères et sera forcé de reformuler. Ça ne me semble pas acceptable.
> Devrait-on plutôt envisager une limite de 200 caractères ? 250 ?

**Comment by DaFrenchFrog** [comment]
Si on limite à 200 ou 250 caractères autant ne pas en mettre du tout.

Pour moi un tel titre est trop long à lire dans une phase de recherche et prend bcp de place à l'affichage (cartes et fiches). Certaines infos mériteraient d'être sorties du titre pour passer dans la description. Par exemple dans ce cas précis, un titre plus pertinent serait : "Dépenses et recettes des EPCI (avec commune de + de 3500 habitants)".

En revanche et dans le cas de moissonnages il est pour l'instant nécessaire de ne pas avoir de limitations pour éviter les problèmes que tu cites. À travers notre outil on essaie de transmettre les bonnes pratiques et c'est d'ailleurs dans ce genre de cas qu'un documentaliste serait utile pour travailler avec les producteurs de données à l'amélioration des informations qu'ils nous transmettent.

Concernant le cas de la modification a posteriori cela pose effectivement un problème. Dans ce cas, soit on prévoit une alerte lorsque ce cas apparait et qui explique pourquoi on limite le nombre de caractères, soit on met cette limitation en stand-by parce qu'il y a des choses plus prioritaires...

Concernant l'ETQ ce serait : je ne peux rentrer un titre plus long que 100 caractères afin de simplifier la lecture des titres.

**Comment by DaFrenchFrog** [comment]
J'ai jouté une colonne message d'erreur dans le doc source de vérité je pense que ce sera plus pratique.

https://lite.framacalc.org/0c5a3v0z3t-9th0

**Comment by johanricher** [comment]
On n'a pas implémenté de limitation sur le nombre de caractères que les utilisateurs peuvent saisir dans les champs. Ce n'est pas un besoin actuellement.


A titre d'exemple, il existe dans le catalogue du MC [un jeu de données avec un nom de 261 caractères](https://catalogue.data.gouv.fr/fiches/d447c437-fb92-4f94-b3fd-b96be1f1a150).

La limitation à 100 caractères ne pourrait donc pas être appliquée, à moins de corriger en amont toutes les valeurs concernées.
