### ISSUE TITLE
Définir un statut d'ouverture ne tenant pas compte de la présence d'un lien ou non

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#265]
# Problème

Certaines fiches de données comme [celle-ci](https://catalogue.multi.coop/fiches/192b4aa5-f3e1-4e45-b084-1a2b5bb9040c) possède un lien d'accès mais il est soumis un login (site intranet).

# Solution

A préciser.

Dans le parcours de contribution le choix du statut d'ouverture devrait être plus précis et ne pas dépendre de la présence ou non d'un lien

**Comment by johanricher** [comment]
Ce lien vers l'intranet du MC n'a rien à faire dans ce champ où il est dit "Page open data : Si le jeu de données est publié en open data, saisissez ici le lien de la page web associée."

**Comment by florimondmanca** [comment]
Je retombe sur ce ticket, je constate que dans la maquette il est proposé d'avoir :

* La possibilité de dire si le jeu de données est opendata : oui/non
* Un champ "Page web" qui n'est pas nécessairement une page open data (mais on sous-entend que si on répond "open data : oui", on peut ici mettre la page open data ?)

**Comment by DaFrenchFrog** [comment]
Oui tout à fait. À valider avec @johanricher mais je le vois comme suit :
- Si je sélectionne OUI (open data), alors le champ page web est obligatoire
- Si je sélectionne NON (pas open data), alors on ajoute un warning pour rappeler les règles de l'open data et le champ de saisie est optionnel.

**Comment by johanricher** [comment]
Selon moi ce warning est un anti-pattern. Ce n'est pas un formulaire de publication d'un jeu de données, c'est un formulaire où l'on peut renseigner les informations factuelles qu'on connait concernant un jeu de données.
* Soit le jeu de données est déjà publié et on uniquement besoin 1) de l'URL de la page où il est publié 2) de la licence qui a été choisie
* Soit le jeu de données n'est pas publié, et ça n'est pas lié à une opinion ou un choix de la personne qui renseigne des informations (autrement le contributeur n'est pas la personne qui va décider de la publication ni la personne qui va réaliser cette publication sur le portail open data du ministère)

En revanche, ce type d'UX (warning, incentive, pédagogie, nudge, peu importe comment on l'appelle) aurait un sens pour que le niveau d'accès d'une entrée dans le catalogue ne soit restreint que si une exception est justifiée cf. #289.

**Comment by DaFrenchFrog** [comment]
> Selon moi ce warning est un anti-pattern.

Anti-patternle mot est un peu fort :D

Mais je comprends ton point. Peut-être qu'on peut simplement passer le warning en simple encart "information" afin dacculturer le contributeur ?

**Comment by johanricher** [comment]
Je ne suis pas sûr que ce soit une bonne chose de mettre un encart d'information s'il n'a pas de lien de causalité avec ce que la personne qui le lit va saisir comme information. On n'a pas un choix à influencer, on demande une info factuelle et ce qui n'est pas dans le schéma on n'a pas besoin de le demander. Si on devait mettre une explication ça serait plutôt du type "avez-vous cherché ce jeu de données sur le portail open data de votre ministère ?" mais même ça je pense pas que ça soit bien vu.

Par contre là où j'ai changé d'avis (comme quoi !) c'est que la définition du champ "URL" du schéma peut être élargie à des pages web qui ne serait pas publiques.

Par exemple dans le catalogue du MC il y a un jeu de données ["Liste des ingénieurs du patrimoine et des techniciens des services culturels dans les DRAC-CRMH"](https://catalogue.multi.coop/fiches/192b4aa5-f3e1-4e45-b084-1a2b5bb9040c) et dont l'URL indiquée est une page web sur l'intranet (https://semaphore.culture.gouv.fr/web/les-monuments-historiques/listes). Cette information sera consultée au-delà du MC, via catalogue.data.gouv par les membres d'autres organisations et via data.gouv par les citoyens.

Est-ce que donner une URL qui est inutile à des personnes extérieures à l'organisation est une mauvaise chose ?

**Comment by florimondmanca** [comment]
Je ferme suite à discussion en réunion ajd, la suite est donnée ici #300.
