### ISSUE TITLE
Champ "licence"

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#287]
## User story

ETQ contributeur je peux spécifier la licence d'un jeu de données

## Parcours

* Dans la page de contribution ou édition, je peux définir la licence dans un champ "Licence".
* J'accède à la page d'une fiche de données : le cas échéant, la licence est affichée sur la page.

## Critères d'acceptation

* (Must have) Le champ "Licence" est présent dans le formulaire de contribution
* (Must have) Des licences par défaut sont suggérées, mais il est possible d'entrer une valeur quelconque
* (Must have) La licence est visible sur la page d'une fiche de données
* (Must have) Un filtre licence est disponible dans la recherche avancée
  * (Should have) Le filtre licence a une option "Toutes les licences" pour voir les jeux de données "en open data" (quelle que soit la licence)

Pour synthétiser, je propose :

### Schéma

Pas de changement sur [le champ `licence` du schéma Table Schema](https://github.com/etalab/schema-catalogue-donnees/blob/master/schema.json#L220).

* Slug : `licence`
* Titre : "Licence"
* Description : "Licence appliquée au jeu de données."
* Type : string
* Requis : non

#### Backend

Attendre mise à jour du [tableur avec les infos d'implé du schéma](https://lite.framacalc.org/0c5a3v0z3t-9th0). La proposition est d'aligner avec le schéma Table Schema.

#### Front côté formulaire

[voir maquette champ](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2321%3A41777) texte saisie libre (ETQ utilisateur je peux saisir librement le nom d'une licence) + menu déroulant basé sur les données du catalogue (ETQ utilisateur je peux sélectionner une licence déjà présente dans le catalogue) cf. [modèle data.gouv.fr](https://demo.data.gouv.fr/fr/admin/dataset/new/)

#### Front côté fiche

[voir maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2366%3A34655) 

#### Front côté recherche

à maquetter : saisie libre + autocomplétion cf. [modèle data.gouv.fr](https://www.data.gouv.fr/fr/datasets/)

Pour une amélioration de l'implé côté front voir les idées esquissées ci-dessus. Cela ne nécessitera pas de changer le modèle de données.

### Backend

Attendre mise à jour du [tableur avec les infos d'implé du schéma](https://lite.framacalc.org/0c5a3v0z3t-9th0). La proposition est d'aligner avec le schéma Table Schema.

### Front côté formulaire

[voir maquette champ](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2321%3A41777) texte saisie libre (ETQ utilisateur je peux saisir librement le nom d'une licence) + menu déroulant basé sur les données du catalogue (ETQ utilisateur je peux sélectionner une licence déjà présente dans le catalogue) 

### Front côté fiche

[voir maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2366%3A34655) 

### Front côté recherche

à maquetter : saisie libre

Pour une amélioration de l'implé côté front voir les idées esquissées ci-dessus. Cela ne nécessitera pas de changer le modèle de données.

## Could have

* Formulaire : [modèle data.gouv.fr](https://demo.data.gouv.fr/fr/admin/dataset/new/)
* Rechercher : [modèle data.gouv.fr](https://www.data.gouv.fr/fr/datasets/)

## Implémentation

Endpoints côté back:

- `POST /datasets/` - Accepte un champ `license: string`. Il est stocké en DB dans un `VARCHAR dataset.license`.
- `GET /licenses/` - Renvoie une liste `string[]` de toutes les licences dispo en base. Calculé par un `SELECT DISTINCT license` pour l'instant. Permet de réutiliser le SearchableSelect en l'état, sans besoin de créer un mécanisme de search-as-you-type propulsé par le back.
- `GET /datasets/filters/` - À mettre à jour pour ajouter `licenses: string[]` (même contenu que `GET /licenses/`).

**Comment by DaFrenchFrog** [comment]
Question @johanricher :
https://www.data.gouv.fr/fr/pages/legal/licences/

Quelle licence devrait être choisie pour dire que la fiche n'est pas accessible au public (pour éviter de dire open data)

**Comment by DaFrenchFrog** [comment]
@johanricher Je comprends ton point mais cette solution est une vision très orientée "data" et on passe à côté de la vision d'accompagnement et d'ouverture (je parle d'ouverture aux utilisateurs moins techniciens) du catalogue...

La liste des licences serait définie par les entrées précédentes ou bien elle sera implémentée comme pour la couverture géographique ?

**Comment by johanricher** [comment]
Peux-tu expliquer ce que tu entends par "vision d'accompagnement et d'ouverture (je parle d'ouverture aux utilisateurs moins techniciens) du catalogue" ? Peux-tu le présenter sous forme de problème à résoudre, de scénario utilisateur ou quelque chose de similaire ?

Ce que je disais tout à l'heure c'est qu'on pourrait par la suite imaginer plein de chose pour rendre l'information plus intuitive.
Par exemple afficher un gros visuel :unlock: "OPEN DATA" si une licence open data est présente.
Et expliciter les droits de réutilisations qui correspondent à la licence, comme le font Github et Gitlab (cf. capture d'écran ci-dessous).
Et simplifier la recherche avec un filtre "open data" si une licence open data est indiquée ou non.
Et... etc.

[![image](https://user-images.githubusercontent.com/10212787/175350477-4a9214ea-a8fa-43b2-8565-e4b3da72900c.png)](https://github.com/etalab/catalogage-donnees/blob/master/LICENSE)

En tout cas un champ "open data : oui/non" ça ne veut strictement rien dire et ça nous mène dès le départ à collecter et donner des informations limitées et donc incorrectes.

> La liste des licences serait définie par les entrées précédentes

Oui car on n'a pas vocation à créer et maintenir une liste exhaustive de licences.

Le ministère de la culture a déjà un catalogue de jeux de donnée ouverts : data.culture.gouv.fr. La licence est indiquée pour chaque jeu de données publié. Donc l'information de la licence existe déjà et ils n'ont pas besoin de la collecter à nouveau pour catalogue.data.gouv.fr Tous les jeux de données sur data.culture.gouv.fr ont vocation à être référencés dans leur catalogue sur catalogue.data.gouv.fr (avec l'info sur la licence), aux côtés des jeux de données qui n'ont pas encore été ouverts.

**Comment by DaFrenchFrog** [comment]
"Je suis responsable du pôle Archéologie de la DRAC Bretagne et je souhaite ajouter la liste des sites archéologique de ma région. Ce fichier contient des adresses non diffusables (pour les risques de pillage) donc ce fichier n'est pas en open data. Je ne connais pas bien les licences d'utilisation."
-> Problème : on ne sait pas quelle licence choisir (en fait on ne doit en mettre aucune mais comment le deviner ? et je ne peux pas indiquer qu'une demande peut être formulée pour avoir accès au fichier)
"J'ai créé un fichier contenant la liste des oeuvres présentes au musée du Louvre et je souhaite les ajouter au catalogue. Je n'y connais rien aux licences d'utilisation mais je sais que ce fichier est public."
-> Problème : s'il y a plusieurs licences ouvertes on ne saura pas laquelle choisir.

Il n'est pas sûr que l'on n'ait pas vocation à maintenir une liste de licence. C'est justement cette notion de service que l'on rend aux utilisateurs à travers le rôle de documentaliste que nous avons recommandé d'avoir.

Mais je peux prototyper la solution envisagée et on organisera des tests pour voir si cela fonctionne...

**Comment by johanricher** [comment]
> "ce fichier n'est pas en open data"

Donc il n'a pas de licence, tout simplement. 

> "Problème : on ne sait pas quelle licence choisir"

Décrire un jeu de données ce n'est pas ouvrir le jeu de données ou le publier sur un portail open data. Donc on ne demande pas de faire un choix mais de donner des informations factuelles ET connues du contributeur.

> "Je n'y connais rien aux licences d'utilisation mais je sais que ce fichier est public."

Si le fichier est "public", il a été publié sur une page web et il doit y avoir l'information de licence indiqué sur cette même page. Le contributeur peut ajouter l'information de la licence sur la fiche catalogue.data.gouv.fr en la copiant à partir de cette page. Si le contributeur ne trouve pas l'information il ne met rien. Si une licence n'a pas été indiquée c'est que le jeu de données n'est pas en open data (même s'il est "public") donc il ne met rien.

---

De manière générale un contributeur est par définition une personne qui a une information à ajouter au catalogue. S'il ne sait pas, il ne met rien. Il faut que l'UX soit extrêmement claire là-dessus !

**Comment by DaFrenchFrog** [comment]
@johanricher Ok alors voici ce que je propose pour que ce soit fluide pour l'utilisateur :
- Un a d'abord champ unique "Ce jeu de données est-il en open data ?"  OUI/NON (ce champ n'est pas suavegardé)
- Si OUI, deux champs **obligatoires** apparaissent : "lien vers la page open data" et "licence d'utilisation"
- Si NON, seul un champ optionnel apparait "Lien vers les données"

On pourra ajouter un descriptif pour détailler l'utilisation de ces champs.

Dans la fiche de données, si il y a une licence saisie alors on affiche le statut "open data", sinon on affiche le statut "restreint" (ou un autre terme qui indique que la donnée n'est pas open data.

Est-ce que cela conviendrait ?

**Comment by florimondmanca** [comment]
@DaFrenchFrog Je comprends l'idée, mais je dois relever la complexité associée à ce mécanisme.

En effet, pour l'implémentation il faut résoudre un certain nombre de questions de comportement.

En particulier, un radio group de ce type est tri-état : oui, non, N/A (aucun radio button sélectionné). Dans la page de contribution, on démarre à l'état N/A. Ensuite l'utilisateur peut éventuellement choisi oui ou non.

Si on accède ensuite à la page d'édition. comment décider s'il faut initialement afficher oui, non, ou N/A ? La règle semble être : "oui" s'il y a une `url` et une `license`, "non" s'il y a seulement une `url`, N/A s'il n'y a ni `url` ni `license`. Mais si je coche "non" et que je laisse `url` vide (champ optionnel), la règle précédente amène à afficher N/A, car `license` et `url` seront vides. Pourtant l'utilisateur aura coché "non" ! J'en conclus que, contrairement à ton hypothèse ("ce champ n'est pas sauvegardé"), on devrait en réalité stocker cette information oui/non en base. Mais il faudrait dès lors s'assurer de la cohérence entre ce champ, `url` et `license` côté back. Mais on constaterait une redondance entre ce nouveau champ et `license` lequel vraiment utiliser dans l'affichage "Open data" ou "Restreint" ?

Bref, je rejoins Johan sur le constat que cette façon de présenter les choses induit une incohérence / redondance dans l'information manipulée. Ça amène à une bien plus grande complexité que 2 champs séparés, pour un bénéfice UX qui est peut-être réel, mais qui me semble bien moindre en proportions.

Que donnerait une interface avec 2 champs séparés? La description du "Lien vers les données" pourrait inviter à renseigner spécifiquement la page dite "open data". Mais au fond, la contribution ferait le travail : si une page "version portail interne" est renseignée, alors qu'on affiche "Open data" (puisqu'il y a une licence), l'incohérence amènerait les contributeurs à trouver et renseigner la page open data.

**Comment by DaFrenchFrog** [comment]
N/A ne peut pas être valide dans la saisie du formulaire. On doit obligatoirement répondre oui ou non. Et seulement après le clic sur une réponse on affiche les champs correspondant.
Par conséquent on ne peut pas retrouver dans l'édition le statut N/A du champ. S'il n'y a ni url ni licence c'est "non" qui doit être coché.

Pour moi ça se tient non ? Peut-etre que ce serait plus simple d'en parler oralement rapidement.

**Comment by johanricher** [comment]
Le chemin "Ce jeu de données est-il en open data ?" OUI/NON ne tient pas ! 

Les champs URL et licence sont complètement dissociés et doivent pouvoir être renseignés séparément et aucun des 2 n'est obligatoire.

* Une URL qui est connue du contributeur ne veut pas dire qu'il connait la licence ou qu'une licence a été choisie
* Une URL existe ne veut pas dire que la page web est publique (URL d'une page sur un intranet, donc pas de licence open data évidemment)

**Comment by johanricher** [comment]
Pour synthétiser, je propose :

### Schéma

Pas de changement sur [le champ `licence` du schéma Table Schema](https://github.com/etalab/schema-catalogue-donnees/blob/master/schema.json#L220).

* Slug : `licence`
* Titre : "Licence"
* Description : "Licence appliquée au jeu de données."
* Type : string
* Requis : non

### Implé

* Backend :  attendre mise à jour du [tableur avec les infos d'implé du schéma](https://lite.framacalc.org/0c5a3v0z3t-9th0). La proposition est d'aligner avec le schéma Table Schema.
* Front côté formulaire : champ texte saisie libre + autocomplétion basée sur les données du catalogue
* Front côté fiche : à maquetter
* Front côté recherche : saisie libre + autocomplétion

Pour une amélioration de l'implé côté front voir les idées esquissées ci-dessus. Cela ne nécessitera pas de changer le modèle de données.

---

Je vous laisse relire cette proposition et la challenger avant que je mette à jour le ticket (et [le tableur schéma](https://lite.framacalc.org/0c5a3v0z3t-9th0)) pour qu'on puisse le passer en "prêt à développer".

**Comment by DaFrenchFrog** [comment]
> Le chemin "Ce jeu de données est-il en open data ?" OUI/NON ne tient pas !

@johanricher On a vu le process avec Florimond et en tenant compte de tes remarques avec lesquelles je suis en phase cela fonctionne. L'idée est d'aller au delà du simple remplissage de champs et de proposer une expérience fluide et qui ne rebute pas l'utilisateur avec des champs sur lequel il a des doutes (voire qu'il ne comprend pas). Mais le mieux est d'en parler de vive voix. @florimondmanca avait commencé à implémenter cette solution mais il reste un sujet un peu plus technique donc on veut être sûrs que tu es ok avec la proposition pour aller au bout.

**Comment by johanricher** [comment]
Ok si vous avez êtes d'accord sur la maquette et l'implé front ça me convient tout à fait. :+1:
