### ISSUE TITLE
Régler le niveau d'accès d'une entrée dans le catalogue

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#289]
A designer et implémenter en lien avec :
* #286

## Contexte

* Un catalogue (de jeux de données) est une liste dont chaque _entrée_ décrit un jeu de données et ses métadonnées ([définitions](https://jailbreak.gitlab.io/investigation-catalogue/synthese.html#/2)).
* "Entrée" = "fiche" (dans le contexte de l'UI de l'outil de catalogage)
* Un catalogue de jeux de données ne contient pas le contenu des jeux de données eux-mêmes.

### Principes juridiques

* Un catalogue de jeux de données est un document administratif communicable ([définition](https://guides.etalab.gouv.fr/juridique/opendata/#qu-est-ce-que-l-open-data)) donc doit être ouvert par l'administration qui le produit (_open data_).

La notion de "partage" est parfois utilisée comme degré intermédiaire sur le spectre de l'ouverture ([The Data Spectrum](https://theodi.org/about-the-odi/the-data-spectrum/), traduit par [Datactivist](https://medium.com/datactivist/ouvrir-ce-nest-pas-juste-partager-des-donn%C3%A9es-simple-basique-ec87d762f2a2)).

Exceptions :

Il peut y avoir des exceptions à la mise en _open data_ de certaines entrées dans le catalogue, qui en font des documents qui ne sont pas "communicables". Deux exemples :
* Si l'entrée est considérée comme un document qui n'est pas "achevé".
* Si le simple fait de faire connaître au public l'existence d'un jeu de données et ses métadonnées (pas le jeu de données lui-même qui n'est pas contenu dans le catalogue) révèle des "secrets légaux" ([définition](https://guides.etalab.gouv.fr/juridique/ouverture/#que-faire-si-mes-documents-administratifs-contiennent-des-secrets-legaux)), par exemple en portant atteinte à la sûreté de l'Etat.

### Fonctionnel

* En tant que (ETQ) contributeur, j'ai besoin de restreindre le niveau d'accès d'une entrée dans le catalogue car elle révèle un secret légal.
* ETQ réutilisateur de jeux de données et agent dans une administration, j'ai besoin de connaître le service ou les personnes qui le produisent dans une autre administration afin de pouvoir demander son partage.
* ETQ réutilisateur de jeux de données et citoyen, j'ai le droit de savoir qu'un jeu de données existe, et j'ai besoin de connaître le service ou les personnes qui le produisent afin de pouvoir demander son ouverture.

### Compréhension

1. En tant que contributeur je dois savoir que, quand je suis dans le formulaire de contribution, **toutes les informations sur cette page sont publiques par défaut**, c'est à dire diffusées en dehors de catalogue.data.gouv.fr.
2. En tant que contributeur, je dois avoir comprendre que **le contenu du jeu de données n'en fait pas partie**.
3. En tant que contributeur, je dois donner **un motif explicite et valide pour que les informations sur cette page ne soient pas publiques**.

## Critère d'acceptation

* Tous les membres d'une organisation (quel que soit leur rôle) peuvent modifier le niveau d'accès d'une entrée dans le catalogue de cette organisation.
* Le niveau d'accès d'une entrée dans le catalogue doit s'appliquer à tous les champs du schéma du catalogue concerné, y compris ses champs complémentaires (i.e. si une fiche a un niveau d'accès "Public", les informations de tous les champs seront publics).
* Par défaut, une entrée a un niveau d'accès "Public". Dans ce cas cette entrée est accessible
  * à tous les utilisateurs sur data.gouv.fr comme une ligne dans le fichier CSV du catalogue publié via l'API de `catalogue.data.gouv.fr` (#286)
  * et à tous les membres de toutes les organisations sur `catalogue.data.gouv.fr` comme une fiche visible dans l'UI.
* Si une exception s'applique, le niveau d'accès pourra être réglé sur "Restreint". Dans ce cas cette entrée est accessible
  * seulement aux membres de l'organisation.
* Il ne doit pas y avoir d'ambiguité entre la "fiche" d'un jeu de données (je dois comprendre qui a accès à ces informations) et les métadonnées du jeu de données lui-même (je dois comprendre si le jeu de données est ouvert ou pas et sous quelle licence).

## Implémentation

TODO

## Idées pour la suite

* Définir le niveau d'accès champ par champ (uniquement pour les champs complémentaires).

**Comment by florimondmanca** [comment]
@johanricher Suite à la réunion d'équipe de ce jour, cette notion de "régler un niveau d'accès" a-t-elle encore un sens ? En tout cas, est-ce encore dans le scope pour ce milestone ?

D'après la [maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes) de @DaFrenchFrog, on aurait plutôt une information "open data ou pas", et une URL indépendante (ajd cette URL est une URL d'open data). On s'en contenterait donc ?

**Comment by johanricher** [comment]
Cette feature est bien un must have.

> "open data ou pas"

Ca c'est une métadonnée du jeu de données (qui appartient au schéma). Le niveau d'accès est une métadonnée de la "fiche" (autrement dit une entrée dans le catalogue).

> Malheureusement dans la maquette (à date), je pense que la confusion/ambigüité entre "fiche" et "jeu de données" est encore présente. 

En effet, la façon dont cette info de niveau d'accès apparait dans l'UI doit encore être designée. A mon sens il faut qu'elle ce soit bien séparée des métadonnées du jeu de données (nom, description, URL, licence...).

> 2 niveaux : "Public" et "Partagé aux autres organisations"

C'est en effet ce qu'on retient comme "must have" pour l'implémentation de cette feature. Je vais mettre à jour la description.

**Comment by johanricher** [comment]
Le niveau d'accès d'une fiche n'a aucun lien avec le fait que le jeu de données décrit par la fiche soit en open data ou pas.

Ce ticket est à designer et implémenter dans le cadre du multi-catalogue (epic #122). Ca n'était indiqué qu'à la fin du ticket, je vais le mettre en haut pour que ce soit plus clair.

**Comment by DaFrenchFrog** [comment]
J'ai bien compris mais nous avions dit que pour le prochain milestone toutes les fiches étaient visibles par un utilisateur (connecté) quelle que soit son organisation. Si on maintient cette idée je pense que ce ticket peut attendre non ?

**Comment by florimondmanca** [comment]
@DaFrenchFrog Hello, suite à la priorisation de jeudi dernier, pour la suite il faudrait d'abord maquetter à quoi ceci pourrait ressembler ? Sachant qu'il faut d'abord passer en revue le ticket pour vérifier s'il est clair et complet (je mettrai un autre commentaire plus tard avec mes éventuelles questions).

**Comment by DaFrenchFrog** [comment]
@johanricher est-ce que ces deux user stories doivent être implémentée pour le prochain milestone ? Elles me semblent assez complexes au stade où on en est non ?

> ETQ réutilisateur de jeux de données et agent dans une administration, j'ai besoin de connaître le service ou les personnes qui le produisent dans une autre administration afin de pouvoir demander son partage.

Est-ce que cela signifie que toutes les fiches sont visibles par les autres organisations mais on ne verrait que le titre et les contacts ?

>ETQ réutilisateur de jeux de données et citoyen, j'ai le droit de savoir qu'un jeu de données existe, et j'ai besoin de connaître le service ou les personnes qui le produisent afin de pouvoir demander son ouverture.

Ici pour répondre à cette US il nous faut avoir une page publique non ?

**Comment by johanricher** [comment]
Ce qu'on a décidé c'est que c'était un des prochains tickets à attaquer (4ème dans la suite). La finalisation des tâches (fermer le ticket) pourrait avoir lieu après le 13/10.

Les user stories ne servent qu'à éclairer des besoins métiers la réalité complexe à laquelle on est confrontée. En l'occurence le besoin d'une persone de connaître des informations est contredit par le besoin d'une autre personne de cacher une information (par exemple pour des raisons légales). Il est nécessaire de comprendre les deux.

**Comment by DaFrenchFrog** [comment]
OK. Pour moi la première étape consiste simplement à faire ceci :
- Formulaire de contribution : ajouter un champ intitulé "Cette fiche est-elle visible par les membres des autres organisations"  ayant pour valeurs "Oui" ou "non"
- Fiche de données : une mention qui indique que seuls les membre de l'organisation peuvent consulter cette fiche

Les membres d'une autre organisation ne verront simplement pas cette fiche. Je précise que cette demande est remontée de plusieurs responsables d'organisation.

**Comment by johanricher** [comment]
Suite à la discussion d'aujourd'hui on décide d'approfondir l'exploration sur ce ticket. Dans un premier temps c'est un travail de @DaFrenchFrog (maquette et/ou autres éléments).

L'objectif, et critère d'acceptation principal, c'est que n'importe quel utilisateur, au moment de finaliser sa contribution (création ou édition d'une fiche), comprenne ("consentement éclairé") :
1) par défaut, qui aura accès aux informations
2) si l'accès aux informations doit être restreint, pour quelle raison

**Comment by DaFrenchFrog** [comment]
@johanricher @Volubyl Voici une proposition de maquette pour permettre au contributeur de masquer une fiche aux autres organisations.

- On introduit dans le champ lexical la notion de **"fiche catalogue"**. Cela devrait permettre une meilleure distinction entre "jeu de données", "métadonnées d'un jeu de données", et "méta-données de la description du jeu de données".
- On ajoute en haut de la page de contribution un panneau d'information refermable qui rappelle les enjeux de l'ouverture des données et les raisons pour lesquelles on pourrait ne pas ouvrir un document administratif.
- On ajoute une rubrique "Visibilité de la fiche catalogue" avant les liens vers les données qui là encore renforce la distinction ouverture/visibilité
- On pose une question précise et binaire, pour proposer au contributeur de masquer cette fiche aux autres organisations. **La case est cochée "Oui" par défaut**.
- Si le contributeur coche "Non", alors on ouvre une fenêtre modale lui rappelant les règles applicable ainsi que le fait que ce n'est pas parce qu'une donnée n'est pas publique qu'elle doit forcément être masquée aux autres organisations.
- Sur la fiche catalogue, dans le cas où la fiche est masquée aux autre organisations on ajoute un [bandeau d'information importante](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bandeau-d-information-importante) pour indiquer que la fiche est masquée aux autres organisations.

 - Maquette contribution : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2373%3A37961
- Maquette de la fiche catalogue : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2366%3A34655

Voilà n'hésitez pas à me dire ce que vous en pensez.

**Comment by johanricher** [comment]
Merci Romain

Il manque il me semble une solution en réponse aux remarques que tu émettais sur l'ambiguité de la publication des informations contribuées, à la fois dans l'UI aux "autres organisations" mais aussi via l'API (c'est à dire en pratique un fichier complet du catalogue potientiellement publié en open data sur data.gouv.fr ou ailleurs). Il semblait nécessaire suite à cette discussion qu'au moment de sa contribution la personne sache clairement _qui_ aura accès aux informations qu'elle apporte.

Indiquer qu'une "fiche est masquée aux autres organisations", et la notion de "fiche" elle-même, me semble donc insuffisant pour lever cette ambiguité. 

Pour itérer sur cette exploration, je soumets quelques idées, encore à l'état de brainstorming :

Sur le formulaire de contribution :
* L'accès aux informations contribuées sur cette page doit être restreint : oui / non
  * Oui : choisir une option parmi plusieurs (à minima "Non achevé", et "Secret légal")
  * Non. 
Un panneau d'information serait utile ici 1) pour que le contributeur choisisse la bonne option si l'une d'entre elles s'applique et 2) informer sur le fait que les informations contribuées sur cette page seront visibles de toutes les organisations et publiées en open data.

Sur la fiche :
* Accès restreint : "L'accès à ces informations est restreint" / "Seuls les personnes faisant partie de votre organisation peuvent lire ces informations")
* Accès non restreint : "Les informations visibles sur cette page sont accessibles à tout le monde."

La formulation et les termes utilisées sont à améliorer pour que ce soit le plus limpide possible (tout en étant factuel et précis, notamment du point de vue légal).

Panneau "À propos de l’ouverture des jeux de données" : il n'est pas utile au moment de la contribution puisque 1) soit le jeu de données est déjà ouvert, donc le contributeur n'a pas besoin d'être informé sur ça, 2) soit le jeu de données n'est pas encore ouvert et ce n'est pas au moment de la contribution que l'ouverture du jeu de données peut se faire, donc le contributeur n'a pas besoin d'être informé. Eventuellement cela pourrait être une information qu'on donne dans le contexte des champs licence et/ou URL, mais plutôt pas affiché par défaut (je ne sais pas quelle est la meilleure option en terme de design et a11y). Et même là je ne suis pas sûr que ça réponde à un besoin ?

**Comment by Volubyl** [comment]
@johanricher j'ai un problème de compréhension avec ce critère d'acceptation : 

> Tous les membres d'une organisation (quel que soit leur rôle) peuvent modifier le niveau d'accès d'une entrée dans le catalogue de cette organisation.

Est-ce que cela veut dire que seuls les membre d'une organisation peuvent définir le niveau d'accès des jeux de donnée de LEUR organisation ?

Exemple : je suis de l'orga A, je ne peux pas définir le niveau d'accès de jeux de données de l'orga B.

C'est ça ?

**Comment by johanricher** [comment]
Oui en effet ! 

Après je me rends pas compte de la complexité de l'implémentation de tous les critères d'acceptation et de l'état du travail que tu es en train de faire. Le plus prioritaire c'est qu' "on puisse" (quelque soit la méthode implémentée) faire en sorte que certaines entrées (fiches) du catalogue n'apparaissent plus dans le CSV exporté de ce catalogue. Pour le reste de l'implé, ça peut être itéré dessus.

**Comment by Volubyl** [comment]
j'ai juste ce critère à implem et pour le reste je crois que je suis bon d'ici demain ça sera sur staging

**Comment by johanricher** [comment]
Mais c'est magnifique

**Comment by Volubyl** [comment]
@johanricher pour moi c'est bon tout est sur staging

Je viens par contre de me rendre compte que il n'y a qu'une seule organisation sur staging et donc c'est compliqué de tester les différents cas d'usages qui necéssites d'avoir deux organisations par exemple :

- je suis de l'orga A, je ne peux pas changer le niveau d'accès d'un jeu de donnée de l'organisation B

Par contre, ce que tu peux d'ores et déja tester c'est :

- dans l'export CSV il n'y a que des jeux de données publics
- je peux modifier le niveau de visibilité d'un jeu de donnée appartenant à mon organisation

**Comment by johanricher** [comment]
Sur https://staging.catalogue.multi.coop/

J'ai mis [la fiche du jeu de données "Soldat emmener profond"](https://staging.catalogue.multi.coop/fiches/2f03469d-f3af-415f-8829-2fe365447364/) en restreint.

Mais l'entrée "Soldat emmener profond" est toujours [dans le catalogue exporté en CSV](https://staging.catalogue.multi.coop/api/catalogs/11004601800013/export.csv).

**Comment by Volubyl** [comment]
mmmm je sais ce qu'il se passe.

On a un cache de 24h sur l'export des catalogues.

Pour que l'export prenne en compte les changements liés à un dataset il faut attendre 24h00 le temps que le cache s'invalide

Est-ce que dans un cas d'usage du "monde réel", il serait ok que pdt 24h00 l'export affiche encore les jeux de données "restreints" ?


Je demande pcq l'invalidation de cache c'est pas un petit sujet ...  :-s

**Comment by johanricher** [comment]
> On a un cache de 24h sur l'export des catalogues.

J'avais oublié ! 

> Est-ce que dans un cas d'usage du "monde réel", il serait ok que pdt 24h00 l'export affiche encore les jeux de données "restreints" ?

Oui !

1. Si on peut expliciter ça dans la description de la doc OpenAPI du endpoint, ça serait mieux.
2. On verra plus tard si une mise à jour plus fréquente du cache est nécessaire.

**Comment by johanricher** [comment]
En tout cas, à part le fait que je peux pas valider certains critères sur staging, le reste de l'implé pour moi c'est bon ! Super travail ça rend très bien dans le front et l'UX me paraît claire.  Je laisse @DaFrenchFrog donner son avis. Il me semble qu'il manque des liens (notamment un sur "secrets légaux" qui pointe vers [le guide Etalab](https://guides.etalab.gouv.fr/juridique/ouverture/#que-faire-si-mes-documents-administratifs-contiennent-des-secrets-legaux)) mais ils n'étaient peut-être pas dans la maquette. On pourra les ajouter et globalement tweaker ces détails d'UI dans un second temps.

En résumé pour moi c'est donc LGTM. :rocket:

**Comment by Volubyl** [comment]
> Je demande pcq l'invalidation de cache c'est pas un petit sujet ... :-s

Ah rectification c'est pas si compliquer que ça d'invalider le cache dans notre cas. 

Cependant, pour moi l'intérêt du cache c'est qu'il reste persité un petit bout de temps (ici 24h00). La question que l'on peut se poser c'est est-ce que c'est tolérable que l'export ne reflète pas les changements apportés à un dataset pdt 24h00.

Je te laisserai répondre à la question :-)

> Il me semble qu'il manque des liens (notamment un sur "secrets légaux" qui pointe vers [le guide Etalab](https://guides.etalab.gouv.fr/juridique/ouverture/#que-faire-si-mes-documents-administratifs-contiennent-des-secrets-legaux)) mais ils n'étaient peut-être pas dans la maquette

Ha justement, en faisant l'implem je me suis rappelé qu'il y avait ce genre de subtilité. Je n'en ai pas trouvé trace dans les maquettes, mais si @DaFrenchFrog tu pouvais m'indiquer où je peux trouver ces infos je ferai les modifs

> On pourra les ajouter et globalement tweaker ces détails d'UI dans un second temps

Je préfère avoir les retours UI de @DaFrenchFrog, les faire et puis merger sur main. Pour moi cela indiquera que cette feature est considérée comme terminée et que je peux passer sereinement à autre chose :-)

J'ai peur que le plus tard n'arrive jamais alors autant que tout soit ok avant de déployé sur la prod

**Comment by johanricher** [comment]
@DaFrenchFrog Est-ce que tu peux mettre à jour la maquette avec le wording qu'on avait décidé pour que @Volubyl puisse l'implémenter : https://pad.incubateur.net/qHpKtyCGRTyxU2nUSw3xMA. C'est l'option 1 des textes qu'on va tester dans un premier temps, et on itérera dessus si ça révèle des incompréhensions.

**Comment by DaFrenchFrog** [comment]
Si la rectification prend 24h il faut absolument l'indiquer à l'utilisateur au moment où il fait ce changement sinon tout ce qu'il va voir c'est un bug (et il faut que l'on s'entende sur le fait que quasiment personne va lire la doc, même si l'indiquer est effectivement nécessaire aussi...)

Si par "invalider le cache" on entend le fait que la modification soit impactée immédiatement alors je pense que ça vaut le coup d'étudier de près ce sujet puisqu'on parle de rendre un JDD invisible pour des raisons de secret légal. Il est possible que le sujet soit suffisamment critique (présence de données personnelles, etc.) pour que la mise à jour devienne urgente.

Pour ce qui est du wording je ne suis pas sûr de savoir de quoi on parle. A mon sens c'est à jour et en accord avec ce qu'on a mis sur le pad. Il y a aussi le lien sur les secret légaux ([https://guides.etalab.gouv.fr/juridique/ouverture/#que-faire-si-mes-documents-administratifs-contiennent-des-secrets-legaux](https://guides.etalab.gouv.fr/juridique/ouverture/#que-faire-si-mes-documents-administratifs-contiennent-des-secrets-legaux))

<img width="920" alt="image" src="https://user-images.githubusercontent.com/25462034/203963106-808ba497-4e29-44bb-bac2-dce0c4be57e8.png">

**Comment by DaFrenchFrog** [comment]
Il manque également le lien vers le endpoint CSV sur staging.

**Comment by johanricher** [comment]
Le texte dans les maquettes ne correspond à celui qu'on a écrit ensemble sur le pad. On peut en rediscuter pour le finaliser avant la mise à jour des maquettes.

Le délai de 24h ne concerne que l'export en CSV via l'API, et le seul endroit depuis lequel on peut télécharger le CSV est la doc de l'API pour ce endpoint, donc cette information me paraît utile à cet endroit (pour comprendre le fonctionnement de l'API). Je ne crois pas que ce soit une information utile à l'utilisateur de l'UI pour en comprendre le fonctionnement donc ça risque de générer chez lui une incompréhension voire un blocage.

**Comment by johanricher** [comment]
@Volubyl Les maquettes sont à jour, tu peux les prendre en compte :
* [Formulaire de contribution](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2373%3A37961&t=cOcTHNXnfkgiy9UI-4)
* [Fiche](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2366%3A34655&t=cOcTHNXnfkgiy9UI-4) (attention au tooltip)

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog 

Je copie colle ici mon message  que j'ai mis sur figma

Je n'ai pas l'impression que le message "  Par défaut, les fiches catalogues publiées sont accessibles au public (via API)."

Dans les faits, les fiches catalogues sont accessibles via l'interface graphique (le site sur lequel la personne voit ce message) ET aussi via l'API

La phrase "Par défaut, les fiches catalogues publiées sont accessibles au public (via API)" induit, pour moi, que les visiteurs peuvent avoir accès aux fiches catalogues UNIQUEMENT via l'API ce qui est faux.

Je pense que l'on devrait enlever le "via API" car je n'ai pas l'impression que ce soit une info essentielle pour l'utilisateur lambda

Cependant, si l'on veut tout de même parler de cette API on pourrait rajouter qqch dans ce goût 

"[...] sont accessibles au public et seront aussi reprises dans l'export via l'API"

Vous en pensez quoi ?

**Comment by DaFrenchFrog** [comment]
> La phrase "Par défaut, les fiches catalogues publiées sont accessibles au public (via API)" induit, pour moi, que les visiteurs peuvent avoir accès aux fiches catalogues UNIQUEMENT via l'API ce qui est faux.

Pourtant c'est vrai non ? Le public (sous entendu tout citoyen ne faisant pas partie d'une organisation) ne peut accéder à ces fiches qu'en passant par l'API puisqu'il faut se connecter pour les consulter.

**Comment by Volubyl** [comment]
Hein je pense que j'avais mal lu 

sont accessibles **au public** sous-entendu à toute personne n'ayant pas forcément un compte pour accéder à catalogage

Ok ça fait plus sens avec cette précision

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog j'ai fait les retours. C'est déployé sur staging.

Dites moi si c'est ok pour vous

@johanricher j'ai bien mis un message dans la doc de l'API mais comme le lien pointe vers la version qui est sur la prod il faudra attendre que je déploie sur la prod pour le voir apparaître.

Quand ce sera bon sur vous je le ferai :-)

**Comment by johanricher** [comment]
Oui pour moi c'est bon. Il y aura sûrement matière à affiner le wording pour éviter les éventuelles ambiguités restantes pour pour moi on a au moins résolu les problèmes d'incompréhension qu'on avait détectés.

Petite coquille : le lien "secrets légaux" ne pointe pas vers la bonne ancre, c'est celle-là qu'il faut utiliser : `https://guides.etalab.gouv.fr/juridique/ouverture/#que-faire-si-mes-documents-administratifs-contiennent-des-secrets-legaux`

**Comment by Volubyl** [comment]
@johanricher c'est en prod

**Comment by johanricher** [comment]
Encore un gros epic mis en prod en beauté, merci à tous !
