### ISSUE TITLE
Champ 'url'

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#300]
### Schéma

Pas de changement sur [le champ `url` du schéma Table Schema](https://github.com/etalab/schema-catalogue-donnees/blob/master/schema.json#L202).

* Slug : `url`
* Titre : "URL"
* Description : "Page web du jeu de données."
* Type : string
* Requis : non

### Implé

* Backend : `published_url` -> `url`
* Front côté formulaire : champ texte saisie libre (pas d'autocomplétion, et vérification minimale que le format URL est respecté). A priori rien à changer ?
* Front côté fiche : [voir maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1578%3A48732). A priori rien à changer ?
* Front côté recherche : on n'implémente pas ce champ côté recherche.

**Comment by florimondmanca** [comment]
@DaFrenchFrog Comment tu verrais champ redéfini dans la maquette ? Pour suivre la dernière version, un champ "Page web associé aux données" optionnel, plus caché derrière interface oui/non (cf #287) ?

**Comment by DaFrenchFrog** [comment]
Pour répondre à cette question il me manque des réponses sur #287

**Comment by johanricher** [comment]
Pour synthétiser, je propose :

### Schéma

Pas de changement sur [le champ `url` du schéma Table Schema](https://github.com/etalab/schema-catalogue-donnees/blob/master/schema.json#L202).

### Implé

* Backend :  attendre mise à jour du [tableur avec les infos d'implé du schéma](https://lite.framacalc.org/0c5a3v0z3t-9th0). La proposition est d'aligner avec le schéma Table Schema. A priori le seul changement serait : `published_url` -> `url`
* Front côté formulaire : champ texte saisie libre (pas d'autocomplétion, et vérification minimale que le format URL est respecté). A priori rien à changer ?
* Front côté fiche : [voir maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1578%3A48732). A priori rien à changer ?
* Front côté recherche : on n'implémente pas ce champ côté recherche.

---

Je vous laisse relire cette proposition et la challenger avant que je mette à jour le ticket (et [le tableur schéma](https://lite.framacalc.org/0c5a3v0z3t-9th0)) pour qu'on puisse le passer en "prêt à développer".

**Comment by Volubyl** [comment]
Pour moi pas d'objection! On la passe à prêt à développer ?
