### ISSUE TITLE
CSS spinner

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#325]
Code HTML pour le spinner
`<div class="spinner"></div>`

Code CSS

`       
 .spinner {
          display: inline-block;
          width: 50px;
          height: 50px;
          border: 3px solid rgba(0, 0, 0, 0.1);
          border-radius: 50%;
          border-top-color: #000091;
          animation: spin 1s ease-in-out infinite;
          -webkit-animation: spin 1s ease-in-out infinite;
        }
        @keyframes spin {
          to {
            -webkit-transform: rotate(360deg);
          }
        }
        @-webkit-keyframes spin {
          to {
            -webkit-transform: rotate(360deg);
          }
        }
`

**Comment by florimondmanca** [comment]
@Volubyl L'idée serait d'utiliser ce spinner pour l'afficher lorsqu'on charge des données, qu'on éviterait de charger dans le `load()` (time-to-first-print trop allongé), c'est ça ?

**Comment by Volubyl** [comment]
@florimondmanca en effet, ça m'a été utilie dans le cadre de cette issue #373
