### ISSUE TITLE
ETQ administrateur je dois être capable de paramétrer un catalogue personalisé pour mon organisation

### ISSUE THREAD

**Issue by Volubyl** [etalab/catalogage-donnees#338]
Refs #284 
Depend de #334 

## User stories

> ETQ responsable du projet catalogue.data.gouv.fr au sein de la DINUM, j'ai besoin de pouvoir créer un catalogue sur catalogue.data.gouv.fr afin de répondre à une demande dans un ministère

## Critères d'acceptation

> (Must have) Un administrateur peut créer un catalogue depuis l'UI de catalogue.data.gouv.fr 

## Implémentation

Dans le dossier d'une organisation existe déja un fichier décrivant cette organisation. L'objectif ici est de rajouter un fichier décrivant le catalogue personalisé de cette organisation

`schema.json` - Schéma du catalogue de l'organisation : format [TableSchema](https://specs.frictionlessdata.io/table-schema/#introduction) (cf [schema.json](https://github.com/etalab/schema-catalogue-donnees/blob/master/schema.json))~~ -> fera l'objet d'une autre issue

Pour créer ou modifier une organisation:

1. Créer une PR. Ça déclenche la CI qui va valider le fichiers de description du catalogue.
2. Merger la PR une fois valide. La CI déclenche un job sur `master` qui **ajoute** les orgas nouvelles et leur schéma dans l'outil. NB : **création uniquement**, pas de système de mise à jour/suppression

**Comment by johanricher** [comment]
Puisque on a décidé pendant l'atelier qu'on ne gérait la configuration d'un catalogue (définir les champs complémentaires) qu'à sa création (détaillée ici #284), est-ce qu'on a besoin d'un autre ticket ?

**Comment by florimondmanca** [comment]
Oui c'est vrai. En fait @Volubyl je pense qu'il faut voir #284 et #334 comme deux epics séparées, et pas #334 dépendant de #284.
