### ISSUE TITLE
Vérification du schéma d'un catalogue sans champs complémentaires

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#353]
Utilisé par
* #284 

Mirroir de
* #349 

## Description

Après qu'une organisation ait été créée sur l'instance, ou dans la même PR, la CI doit vérifier que le schéma du catalogue est valide.

Si la vérification de la configuration de l'organisation passe, la CI vérifie aussi le schéma du catalogue.

## Critères d'acceptation

* Le schéma d'un catalogue est un Table Schema valide
* Tous les champs du [schéma commun](https://github.com/etalab/schema-catalogue-donnees) sont présents

## Table Schema

* [Spécification](https://specs.frictionlessdata.io/table-schema/)
* Exemple de fichier Table Schema : [schema.json](https://github.com/etalab/schema-catalogue-donnees)
* Implémentation principale : librairie [`frictionless-py`](https://github.com/frictionlessdata/frictionless-py/) ([guide](https://framework.frictionlessdata.io/docs/guides/validation-guide))

Vérification qu'un fichier schéma `schema.json` est valide, via CLI :

```
python3 -m venv venv
source venv/bin/activate
pip install frictionless
frictionless validate schema.json
```

En Python (cf. [guide](https://framework.frictionlessdata.io/docs/guides/validation-guide/#validating-a-schema)) :
```
from frictionless import validate
from tabulate import tabulate

report = validate('schema.json')
errors = report.flatten(['code','message'])
print(tabulate(errors, headers = ['code', 'message']))
```

## Implémentation

* [x] https://github.com/etalab/catalogage-donnees-config/pull/9
* [x] https://github.com/etalab/catalogage-donnees-config/pull/17
* [x] #367

**Comment by Volubyl** [comment]
@johanricher 

Questions pour cette issue :

> Tous les champs du [schéma commun](https://github.com/etalab/schema-catalogue-donnees) sont présents

Actuellement, j'utilise Frictionless pour vérifier si le schéma inclus dans une PR est bien un table schéma (voir [guide](https://framework.frictionlessdata.io/docs/guides/validation-guide/#validating-a-schema))

La validation qui est faite vérifie si le schéma est conforme à TableSchema. 

Ici dans ce critère d'acceptation tu sembles vouloir avoir une validation "plus en profondeure" en vérifiant que le schéma comprends bien que les champs du schéma commun c'est ça ?

**Comment by johanricher** [comment]
Pas d'objection pour isoler et mieux définir ça !

Pour commencer, je reformule une partie de ce que je dis ci-dessus : Si le schéma proposé n'a pas de champ complémentaire, alors le schéma proposé = le schéma commun, et par conséquent c'est aussi un Table Schema valide (puisque le schéma l'est).

> Ici dans ce critère d'acceptation tu sembles vouloir avoir une validation "plus en profondeure" en vérifiant que le schéma comprends bien que les champs du schéma commun.

Il s'agit de vérifier que le schéma proposé dans une PR contient bien tous les champs du schéma commun car c'est le minimum à respecter.

**Comment by johanricher** [comment]
@Volubyl Je vois qu'un autre ticket a déjà été créé pour détailler l'implémentation en backend et une PR a été ouverte pour les travaux sur les champs complémentaires
* #367
* #368

Dans ce contexte je pense que ce ticket a vocation à continuer à servir d'epic pour définir de façon plus générale les critères d'acceptation du point de vue de quelqu'un qui propose l'ajout d'un catalogue avec une PR et les différents cas (avec ou sans champs complémentaires).

Que manque-t-il selon pour comme précision sur 1) la vérification des champs complémentaires dans un schéma et/ou 2) la création d'un catalogue en fonction d'un schéma qui a des champs complémentaires ?

Si ce sont des critères d'acceptation on pourra les ajouter / préciser ici, si ce sont des détails sur l'implémentation technique ce sera plutôt sur #367 et #368.

**Comment by Volubyl** [comment]
@johanricher j'ai créé une issue spécifique pour la vérification des schéma avec champs complémentaire.

Pour moi cela permettrait de plus rapidement clôturer cette issue pcq le code permettant de vérifier un schéma sans champs complémentaire est quasiment prêt.

L'implem des champs complémentaire est encore en cours.
