### ISSUE TITLE
Liste publique des organisations

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#358]
## User stories

* ETQ agent d'un ministère, j'ai besoin de savoir si celui-ci est existe sur `catalogue.data.gouv.fr` afin de savoir si je peux m'enregistrer et me connecter (sinon je dois en faire la demande cf. #334)

## Critères d'acceptation

- [ ] Une page de l'instance doit permettre aux personnes non connectées de voir la liste des organisations (avec ou sans catalogue) qui existent sur `catalogue.data.gouv.fr`.

## Implémentation

En plusieurs étapes :

* [x] Tant qu'il n'y a qu'une organisation, rien à faire.
* [x] On maintient une liste à la main dans la documentation cf. #359 
  * Cf https://github.com/etalab/catalogage-donnees/wiki/Documentation-%C3%A0-destination-des-utilisateurs#quelles-sont-les-organisations-d%C3%A9j%C3%A0-pr%C3%A9sentes-sur-cataloguedatagouvfr-
* [x] On maintient une liste à la main sur la page d'accueil hors connexion (pour chaque organisation : nom, logo, etc.) #483 

## Plus tard

* #488

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog donc si je comprends bien pour le moment je mets seulement les info du ministère de la culture sur la home page ?

Comme sur ce screenshot ?
![Screenshot from 2022-09-21 11-46-45](https://user-images.githubusercontent.com/15958334/191473194-5d052639-4a50-418c-a8fd-b7654ebff38d.png)

**Comment by DaFrenchFrog** [comment]
Oui. Si c'est plus simple tu peux ne pas mettre le nombre de jeux de données.

**Comment by florimondmanca** [comment]
@johanricher Avec #434 il semble qu'on coche le critère d'acceptation de ce ticket ? https://catalogue.data.gouv.fr
