### ISSUE TITLE
Page mentions légales

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#360]
C'est une obligation légale.

# Tâches

- [ ] @johanricher Ecrire le contenu : https://pad.incubateur.net/KF3Y3yZUT4eYgfN4glL_lg
- [ ] Implémenter le contenu dans une nouvelle page `catalogue.data.gouv.fr/mentions-legales`
- [ ] Ajouter lien dans le footer

**Comment by Volubyl** [comment]
@johanricher est-ce que je peux aider en qqch pour obtenir le contenu de cette page ?

**Comment by johanricher** [comment]
On s'inspire des exemples que sont les pages mentions légales de [L’Annuaire des entreprises](https://annuaire-entreprises.data.gouv.fr/mentions-legales) et [api.gouv.fr](https://api.gouv.fr/mentions-legales).

[Voici le draft que je propose pour le contenu de la page](https://pad.incubateur.net/KF3Y3yZUT4eYgfN4glL_lg)

**Comment by florimondmanca** [comment]
@johanricher Je viens de voir que tu avais fait un draft

J'ai aussi regardé les [mentions légales de service-public.fr](https://www.service-public.fr/P10025) en me disant que ce serait une bonne référence. Bingo, ils indiquent les "Mentions légales obligatoires".

Je m'appuie aussi sur [Mentions légales sur votre site internet : les obligations à respecter](https://www.economie.gouv.fr/entreprises/site-internet-mentions-obligatoires

* "Editeur" : Théoriquement il faut indiquer les coordonnées complètes de la DINUM
* J'imagine que l'on tombe dans la catégorie "Site d'information", il manque une section du type "Directeur de la publication" (cf exemple de api.gouv.fr)
* Dans "Hébergement" il y a des informations obligatoires :

    le nom de l’hébergeur
    la raison sociale
    l’adresse
    le numéro de téléphone.

**Comment by johanricher** [comment]
> il faut indiquer les coordonnées complètes de la DINUM 

Tu as raison, j'ai ajouté l'adresse de domiciliation.

>  "Directeur de la publication"

Ok ajouté.

> Hébergement

J'ai ajouté des infos. Pas trouvé de numéro de téléphone en revanche.
