### ISSUE TITLE
ETQ user je peux me connecter via DataPass (Front)

### ISSUE THREAD

**Issue by Volubyl** [etalab/catalogage-donnees#373]
Related to:
* #124 

### Description

L'implémentation de DataPass à été réaliser par Florimond (voir https://github.com/etalab/catalogage-donnees/issues/361)

Maintenant, il est nécessaire d'implementer les différents écrans relatifs aux différentes étapes et cas que l'utilisiateur peut rencontrer lors de sa connexion avec Datapass

### Maquettes 

[En mode non connecté](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2321%3A39720)
[En mode connecté](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2321%3A39720)

### Implémentation

:warning: Le design de la page d'accueil évoluera en fonction de l'avancement de certaines features.

Voir par exemple: #359 , #358 , ...

Cas à couvrir
- [x]  L'utilisateur arrive sur la page et on lui propose de se connecter via Datapass PR : https://github.com/etalab/catalogage-donnees/pull/375
- [x]  un utilisateur peut créer son compte datapass et se connecter à l'application (cas où une seule organisation a été trouvée) PR : https://github.com/etalab/catalogage-donnees/pull/380
- [x] après s'être connecté à Datapass, on indique à l'utilisateur qu'aucune organisation n'a été trouvée PR https://github.com/etalab/catalogage-donnees/pull/379
- [x] après s'être connecté à Datapass, on indique à l'utilisateur que plusieures organisations ont été trouvées PR : https://github.com/etalab/catalogage-donnees/pull/400

Boutons :

* [x] Page d'accueil hors connexion : remplacer boutons "Se connecter" et "S'inscrire" par un [bouton MonComptePro](https://apigouv.notion.site/Interface-guidelines-du-bouton-Mon-Compte-Pro-d316a5c2532d499db9edc3e9d8309602)
* [x] Header hors connexion : supprimer boutons "Se connecter" PR : https://github.com/etalab/catalogage-donnees/pull/421
    * Header connecté : garder le bouton "Deconnexion" (cela ne déconnecte pas de "Mon Compte Pro" mais seulement de l'appli)
  
      PR https://github.com/etalab/catalogage-donnees/pull/410

#### Données sur staging

- [x] ajouter une fixture d'organisation sur le staging via le init data

#### Environnement demo

- [x] Demander à l'équipe api-auth d'enregistrer les URLs de demo (oublié dans https://github.com/betagouv/api-auth/issues/83) Issue : https://github.com/betagouv/api-auth/issues/103

**Comment by Volubyl** [comment]
@DaFrenchFrog j'aurais quelques questions sur la maquette

Pour l'écran qui indique à l'utilisateur que le compte n'est associé à aucune organisation, il y a un lien qui se nomme "la documentation détaillée" vers quel page/site cet url doit pointer ?

Pour le même écran, que fait le boutton "effectuer une demande d'enregistrement"  ?

**Comment by DaFrenchFrog** [comment]
> Pour l'écran qui indique à l'utilisateur que le compte n'est associé à aucune organisation, il y a un lien qui se nomme "la documentation détaillée" vers quel page/site cet url doit pointer ?

Pour moi cela devrait pointer vers un wiki (sur ce repo ?) qui permet d'avoir tous les détails sur l'organisation du service (et donc la création de compte). Ce sera facile à mettre à jour et permettra de valoriser le repo.

> Pour le même écran, que fait le boutton "effectuer une demande d'enregistrement" ?

Plusieurs options sont possible : ce qui j'imaginais c'était le plus simple, un mailto avec en body les informations à saisir traitement de la demande, mais on peut aussi imaginer une page de formulaire (que je devrai maquetter le cas échéant).

@johanricher qu'en penses-tu ?

**Comment by johanricher** [comment]
Les maquettes ne sont pas complètement implémentables en l'état

* on n'a pas pas prévu d'avoir les logos des organisations
* on n'a pas prévu d'afficher une liste des organisations / catalogues qui se met à jour automatiquement

Je proposais dans un premier temps que cette liste soit mise à jour à la main cf. #358

**Comment by johanricher** [comment]
Dans un premier temps la liste des organisations affichées sur la page d'accueil sera en dur (nom de l'organisation, logo, "Catalogue activé" ou "Organisation enregistrée"). On ne met pas le nombre de jeux de données.

**Comment by johanricher** [comment]
> Différents cas :
> - une organisation sans schéma de catalogue
> - une organisation à laquelle plusieurs noms de domaine correspondent
> - une organisation dont un seul nom de domaine d'email correspond 

Cette partie de la description du ticket n'est pas claire pour moi.
@Volubyl Tu confirmes que la notion de nom de domaine n'a plus de sens dans le cadre de #124 ? (à part peut-être dans la connexion legacy ?) Puisqu'avec Datapass on n'a pas besoin de l'adresse email d'un utilisateur donc on ne l'utilise pas ?

**Comment by Volubyl** [comment]
> > Différents cas :
> > 
> > * une organisation sans schéma de catalogue
> > * une organisation à laquelle plusieurs noms de domaine correspondent
> > * une organisation dont un seul nom de domaine d'email correspond
> 
> Cette partie de la description du ticket n'est pas claire pour moi. @Volubyl Tu confirmes que la notion de nom de domaine n'a plus de sens dans le cadre de #124 ? (à part peut-être dans la connexion legacy ?) Puisqu'avec Datapass on n'a pas besoin de l'adresse email d'un utilisateur donc on ne l'utilise pas ?

@johanricher je pense que c'était une mauvaise formulation. J'ai modifié la description

**Comment by Volubyl** [comment]
@florimondmanca par rapport à 

> après s'être connecté à Datapass, on indique à l'utilisateur que plusieures organisations ont été trouvées

J'ai du mal à comprendre dans quel contexte ce cas peut se produire. Tu aurais une idée ?

**Comment by florimondmanca** [comment]
@Volubyl @DaFrenchFrog J'ai ajouté le lien vers les lignes directrices pour le bouton "MonComptePro". Il semble qu'on puisse mettre à jour maquettes / implem pour utiliser ce nom plutôt que "Compte DataPass" ?

**Comment by DaFrenchFrog** [comment]
> @Volubyl @DaFrenchFrog J'ai ajouté le lien vers les lignes directrices pour le bouton "MonComptePro". Il semble qu'on puisse mettre à jour maquettes / implem pour utiliser ce nom plutôt que "Compte DataPass" ?

Les maquettes sont à jour normalement.
