### ISSUE TITLE
ETQ que visiteur je souhaite voir les organismes utilisant l'application de  catalogage

### ISSUE THREAD

**Issue by Volubyl** [etalab/catalogage-donnees#377]
### Description du besoin

En arrivant sur la landing page et sans être connecté, je peux voir un bandeau montrant les différents organismes (ministères, administration, ...) utilisant l'application de catalogage

Maquette https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2385%3A61939

**Comment by Volubyl** [comment]
@johanricher je me demande si cette feature ne serait pas plus intéressante à implémenter dans quelques temps quand on aura déja des organismes ayant adopter l'outil. Qu'en penses tu ?

**Comment by johanricher** [comment]
Je suis d'accord, de façon à implémenter ces maquettes il faudrait prévoir un moyen d'avoir une liste des organisations / catalogues (et infos comme nombre de jeux de données dans le catalogue) qui se met à jour automatiquement donc j'imagine un endpoint API, etc.

Or 1) ce n'est pas dans le périmètre actuel et 2) on peut répondre au besoin ("ETQ agent d'un ministère, j'ai besoin de savoir si celui-ci est existe sur catalogue.data.gouv.fr afin de savoir si je peux m'enregistrer et me connecter") de façon plus simple comme je le propose dans #358 (donc en effet c'est un doublon).

J'ai également répondu la même chose sur les autres tickets :
* https://github.com/etalab/catalogage-donnees/issues/373#issuecomment-1218358604
* https://github.com/etalab/catalogage-donnees/issues/359#issuecomment-1218362390
