### ISSUE TITLE
Mise à jour majeure de Sveltekit

### ISSUE THREAD

**Issue by Volubyl** [etalab/catalogage-donnees#378]
## Description du besoin

Une mise à jour importante de SvelteKit est sortie récement. 

Cette mise à jour peut-être assez tricky à bien effectuer car certains fichiers doivent être renommer, de la config doit être changée etc

Pour avoir un aperçu il y a un [Migration guide](https://github.com/sveltejs/kit/discussions/5774)

Ce serait important d'effectuer cette migration asap parce que le documention de svelte kit prend en compte ces changements et comme la documentation n'est pas versionnée c'est devenu un poil compliqué de s'y retrouver ....

#### la structure du dossier `routes` change

Avant dans le dossier route pouvait avoir cette structure

```
|- blog
|-- index.svelte // Route /blog
```

Dans l'index.svelte, il pouvait y avoir une fonction `load` pour le chargement des données avant l'affichage de la page.

Avec la MAJ, la structure de fichier est la suivante

```
|- blog
|-- index.svelte // Route /blog
|-- index.ts
```

Le fichier index.ts contient la fonction load qui était avant incluse dans le fichier index.svelte

### Procédure

- [ ] Veiller à ce que svelte kit soit bien au moins à la version `@sveltejs/kit@1.0.0-next.405` (en regardaant le package-lock.json)
- [ ] lancer `npx svelte-migrate routes`
- [ ] regarder là où le script à rajouter des "@migrations" (ce sont les endroits où un peu de travail manuel est nécessaire)
- [ ] lancer en local
- [ ] lancer les tests e2e pour voir si tout est ok
- [ ] déployer sur staging

**Comment by Volubyl** [comment]
Au niveau calendrier, je propose de faire cete MAJ APRES avoir fini l'intégration de Datapass

Voir #373

**Comment by florimondmanca** [comment]
## Procédure suivie

(WIP)
1. `npm i --save-dev '@sveltejs/kit'@1.0.0-next.405`
    * La mise à jour avec `@next` ne fonctionnait pas car d'autres changements cassants (nécessitant de changer des choses) ont eu lieu entre la 405 et la dernière version.
1. Retrait de `config.kit.vite` dans `svelte.config.js` comme indiqué
1. La version dans package-lock.json est bien `1.0.0-next.405`.
1. Lancement de `make serve`, une indication apparaît :
    ```
    [client] > svelte-kit dev is no longer available — use vite dev instead
    [client]   1. Install vite as a devDependency with npm/pnpm/etc
    [client]   2. Create a vite.config.js with the @sveltejs/kit/vite plugin (see below)
    [client]   3. Update your package.json scripts to reference `vite dev` instead of `svelte-kit dev`
    ````

    * => `npm i --save-dev vite` et remplacement de `svelte-kit dev` par `vite dev` dans `npm run dev`
    * => Définition de [`server.port`](https://vitejs.dev/config/server-options.html#server-port)`: 3000` dnas `vite.config.js` (le port était devenu 5173)
