### ISSUE TITLE
Nettoyage de l'organisation "legacy"

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#389]
Actuellement, on utilise une organisation dite "legacy" dont le SIRET est 000 000 000 00000 comme "placeholder" : les jeux de données sont rattachés à cette organisation par défaut. Cela a été ajouté dans #351.

Pour pouvoir clore #122, il faut que les fonctionnalités utilisent SIRET explicite partout où c'est nécessaire. Exemples : ajouter un dataset => SIRET nécessaire pour savoir dans quel catalogue l'ajouter ; ajouter un utilisateur => SIRET nécessaire pour savoir à quelle orga l'associer, etc.

Dans le cadre du milestone, l'organisation "legacy" continuera d'exister, mais  et accueillera seulement les utilisateurs admin.

## Critères d'acceptation

* [x] Toute référence à l'organisation "legacy" a disparu du code _[ce point avance au fur et à mesure du passage en mode véritablement multi-catalogue du front]_ https://github.com/etalab/catalogage-donnees/pull/471
* [x] L'organisation "legacy" existe sur l'environnement prod (cf #430)
* [x] L'organisation "legacy" contient un compte ADMIN pour l'équipe produit/dev
* [x] L'organisation "legacy" a un catalogue vide
* [ ] L'organisation "legacy" n'apparaît pas dans les choix du filtre "Catalogue" #489

**Comment by johanricher** [comment]
Comme je disais ici : https://github.com/etalab/catalogage-donnees/issues/334#issuecomment-1252490361

A court terme (livraison 13 octobre) est-ce que c'est un must have de supprimer l'organisation factice (que j'appelle aussi "legacy") ? Celle-ci va devenir invisible (car le contenu de son catalogue supprimé) et seuls les super administrateurs (#288) en feront partie. L'alternative serait de créer plusieurs nouvelles organisations (multi, Fairness, DINUM...) auxquelles les super administrateurs devront appartenir, ça peut être envisagé comme un "should have" mais je ne vois pas d'urgence à cela.

Qu'en pensez-vous ?

**Comment by florimondmanca** [comment]
Oui vu la discussion que l'on a eue, on peut retravailler ce ticket en "Nettoyer l'organisation factice".

Mon objectif était surtout de ne plus faire référence à cette organisation dans le code. Elle pourra exister dans un environnement donné mais on ne doit plus nulle part y ajouter de données (à ce stade elle est encore utilisée comme organisation par défaut dans beaucoup d'opérations du back).

**Comment by florimondmanca** [comment]
@johanricher @DaFrenchFrog Il y a ce critère d'acceptation (proposé par moi)

> L'organisation "legacy" n'apparaît pas dans les choix du filtre "Catalogue"

Qu'en pensez-vous ? L'"Organisation par défaut" apparaît actuellement dans le filtre "Catalogue", est-ce un problème ? Je pensais faire une simple exception dans le code à ce stade pour exclure cette orga des choix du filtre.

**Comment by DaFrenchFrog** [comment]
Je suis pour 👍

**Comment by johanricher** [comment]
Ok :+1:
