### ISSUE TITLE
Bouton Connexion DataPass : 502 Bad Gateway sur staging

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#403]
## Description du bug

Cliquer sur le bouton "Se connecter" (avec DataPass) sur staging génère une erreur 502 Bad Gateway (nginx)

## Comportement attendu

On devrait arriver sur Compte DataPass staging sans erreur

## Comportement réel

Page 502 Bad Gateway renvoyée par Nginx

## Pour reproduire

- Ouvrir https://staging.catalogue.multi.coop
- Cliquer sur "Se connecter" ou "S'inscrire"
- Constater l'erreur 502 Bad Gateway
- Réessayer si besoin : l'erreur semble aléatoire

## Pistes de résolution

* Vérifier les logs de Nginx
* Vérifier l'enchaînement des opérations pour rediriger vers DataPass staging

**Comment by florimondmanca** [comment]
On dirait que le problème vient d'un header trop grand :

```log
022/09/01 08:25:38 [error] 406680#406680: *29488 upstream sent too big header while reading response header from upstream, client: 86.247.63.8, server: staging.catalogue.multi.coop, request: "GET /api/auth/datapass/login/ HTTP/1.1", upstream: "http://127.0.0.1:3579/auth/datapass/login/", host: "staging.catalogue.multi.coop", referrer: "https://staging.catalogue.multi.coop/"
```

Selon cet article cette erreur arrive lorsque [proxy_buffer_size](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size) est trop petit. Selon la documentation :

> Sets the size of the buffer used for **reading the first part of the response received from the proxied server**. This part usually contains a small response header.

Sa valeur est donc la taille maximale de la partie "headers" de la réponse.

Dans mon terminal, https://staging.catalogue.multi.coop/api/auth/datapass/login/ renvoie un header `Set-Cookie` certes long, mais la partie "headers" ne dépasse pas 4096 octets (caractères utf-8), donc augmenter `proxy_buffer_size` ne règlera peut-être pas le problème.

En supprimant le cookie de session sur staging.catalogue.multi.coop, l'erreur a disparu et je n'arrive plus à la reproduire.

**Comment by florimondmanca** [comment]
Puisque ni moi ni @johanricher ne voyons plus la 502 désormais, je vais fermer ce ticket. Si jamais ce pb de 502 quand on bascule sur DataPass se reproduit, on pourra savoir que ça provient sûrement d'un `proxy_buffer_size` insuffisant.

**Comment by johanricher** [comment]
Je confirme c'est bon pour moi merci @florimond !

**Comment by Florimond** [comment]
> Je confirme c'est bon pour moi merci @Florimond !

C'est pas le bon Florimond, mais de rien.

**Comment by florimondmanca** [comment]
J'ai de nouveau ce problème

502 Bad Gateway en cliquant sur "Me connecter avec MonComptePro" sur https://demo.catalogue.multi.coop

Matérialisé par ce message dans les logs d'Nginx

> 2022/10/04 09:00:09 [error] 141202#141202: *4713 upstream sent too big header while reading response header from upstream, client: 86.192.165.21, server: demo.catalogue.multi.coop, request: "GET /api/auth/datapass/login/ HTTP/1.1", upstream: "http://127.0.0.1:3579/auth/datapass/login/", host: "demo.catalogue.multi.coop"

Je crois que @Volubyl l'a rencontré hier aussi.

**Comment by Volubyl** [comment]
indeed!
