### ISSUE TITLE
Envoyer un email aux contacts d'un jeu de données

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#420]
Le bouton est actuellement libellé "Contacter le producteur" sur les fiches jeu de données

### Destinataire

Le champ destinataire doit contenir l'ensemble des emails contenus dans les champs "Adresse e-mail du service producteur" et "E-mail(s) personnel(s)".

### OBJET

`[catalogue.data.gouv.fr] : à propos du jeu de données (nom du jdd)`

### CONTENU

```
Bonjour,
Je prends contact avec vous à propos de ce jeu de données : (mettre l'url).

Saisissez votre message ici...
```

**Comment by johanricher** [comment]
Cette issue n'est pas claire pour moi, est-ce qu'elle concerne le bouton "Contacter le producteur" sur les fiches ? auquel cas il faudrait le préciser
