### ISSUE TITLE
Ajout d'un filtre par organisation dans la recherche avancée

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#431]
Dépend de
* #122

## User Story

ETQ (en tant que) utilisateur, je veux pouvoir choisir une organisation parmi celles présentes sur l'instance lorsque je cherche un jeu de données, afin de pouvoir trouver un jeu de données dans un catalogue spécifique

## Implémentation

Solution générale : ajout d'un filtre "Catalogue" dans "Affiner la recherche" sur la page de recherche

* Ajouter un paramètre `organization_siret` à l'endpoint `GET /datasets/search/`
* Ajouter `organization_siret: List[OrganizationView]` à l'endpoint `GET /datasets/filters/`
* Filtrer les résultats de recherche par : `WHERE catalog_record.organization_siret = <siret>`
* Ajouter le filtre à la UI, selon le même modèle que les filtres existants

## Design

[Voir maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2373%3A38010)

Note : On utilise le terme de "Catalogue" dans l'UI même s'il s'agit d'une liste d'organisations (du point de vue utilisateur ça semble correspondre davantage à ce qui est attendu et compréhensible lors de la recherche, et puisque chaque organisation n'a qu'un seul catalogue il n'y a pas de risque de confusion).

**Comment by florimondmanca** [comment]
J'ai ajouté des détails d'implémentation, de mon point de vue ce ticket est désormais bien défini. Je le passe en "prêt à développer".
