### ISSUE TITLE
Logos des organisations

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#434]
Cf https://github.com/etalab/catalogage-donnees/pull/433#discussion_r974416352

cc @johanricher @DaFrenchFrog pour étude / priorisation

## Problème

Actuellement le logo du Ministère de la Culture est codé "en dur" sous forme de HTML dans les différentes pages : liste des jeux de données, fiche de jeu de données.

Or dans une perspective #122, les organisations auront un logo qui leur est propre.

## Solution envisagée

Stocker les logos des organisations quelque part dans le dossier `client`, et définir un mapping SIRET/logo que l'on utilisera pour afficher le logo. Un composant encapsulerait ces détails : `<OrganizationLogo organization={catalog.organization} />`

## Alternatives considérées

I. Faire la configuration dans le repo de config
  * Ajouter un champ `logo_url` à `Organization`. Il serait **obligatoire**.
  * Dans le repo de config, `organization.json` devra alors contenir un champ `logo_filename` contenant le chemin du fichier relativement au dossier de l'organisation, par exemple `logo.svg` s'il est dans le dossier `organizations/ademe` aux côtés de `organization.json`.
  * Lors de l'upload, le repo de config construira `logo_url` comme URL du logo tel qu'hébergé par le CDN GitHub. Elle sera du type https://raw.githubusercontent.com/etalab/catalogage-donnees-config/master/organizations/ademe/logo.svg. Ce format est considéré comme suffisamment stable pour être utilisé dans un premier temps (cf "Alternatives considérées").
  * Le front utilisera cette URL via le champ `logo_url` pour afficher le logo aux endroits pertinents.
  * (+) Plus pérenne car s'intègre dans le processus de définition des organisations : une seule source de vérité
  * (-) Plus complexe à mettre en oeuvre
  
II. Faire en sorte que le script côté repo de config upload l'image vers nos serveurs : 
  * (-) : Ça demanderait une infrastructure de stockage et service de fichiers dont on ne dispose pas encore, or les délais commencent à se raccourcir.
  * (+) : Ça permettrait de ne pas dépendre du format d'URL utilisé par le CDN GitHub, évitant ainsi de potentiels problèmes si celui-ci change un jour sans rétro-compatibilité (les logos ne s'afficheront plus et il faudra intervenir).

## Décision

L'option "Faire la configuration dans le repo de config" à été retenue

**Comment by johanricher** [comment]
Parfait, on en avait discuté mais ça manquait dans le backlog, merci ! Ca fait partie des "détails" qui vont pointer le bout de leur nez à partir du moment où on sortira du mono- pour entrer dans le merveilleux monde du multi-(organisations, catalogues) !

Dès que #122 est cloturé, on refera un point sur les issues restantes et priorités pour la livraison. Ce ticket n'est pas un "must have" (dans le sens où le service pourra _fonctionner_ sans, ce qui n'est pas le cas d'autres tickets du [milestone](https://github.com/etalab/catalogage-donnees/milestone/3)) mais clairement un gros "should have".

**Comment by florimondmanca** [comment]
Une fois qu'on aura mergé #483, on pourrait créer une version manuelle de ce ticket avec un mapping SIRET / fichier SVG. Ce n'est cependant pas prioritaire selon moi car 1/ Ce ticket concerne des vues "internes", et 2/ On n'a personne de l'ADEME sur l'outil donc le fait qu'on affiche toujours le logo du MC pour le moment n'est pas problématique.

**Comment by Volubyl** [comment]
Pour l'instant, je pense qu'on pourrait partir sur quelque chose de simple à simple. Pour reformuler ce que disait Florimond, une solution simple à implem serait de stocker tous les logos des organisations directement sur le repo.

On pourrait faire en sorte que chaque nom de fichier contenant le logo soit le numéro de SIRET de l'orga.

Pour l'affichage l'on aurait "juste" a afficher le logo qui correspond au siret de l'orga

### Avantages 

- pas long a implem
- ne nécessite pas de moyens techniques supplémentaires (utilisation d'un S3 pour stocker les images, ...)


### Désavantages

C'est une implem manuelle, car cela veut dire que quand on crée une orga sur la repo de config, il faut créer aussi une PR pour rajouter le logo sur le repo "catalogage"

**Comment by johanricher** [comment]
Idéalement le fichier logo devrait pouvoir être proposée dans la même PR qui crée l'organisation, et déclarée dans la config de l'organisation. Mais pour une première itération, la proposition d'implé me convient. TODO : une fois ce ticket fermé, mettre dans le backlog une idée d'amélioration comme 2ème itération.

Dans le cadre cette implé il faudrait quand même prévoir un placeholder (genre logo Marianne) au cas où le fichier logo de l'organisation est manquant (genre dans la période juste après la PR de création de l'orga et avant que la PR du logo ne soit mergée).

**Comment by DaFrenchFrog** [comment]
[Voici la marianne que l'on pourrait utiliser](https://fr.wikipedia.org/wiki/Fichier:Republique-francaise-logo.svg)

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog c'est bon pour moi la feature est sur staging.

Mtn on est en capacité d'ajouter une organisation depuis le repo de config avec un logo.

J'ai rajouté les logos des organisations déja existante en DB.

Sur staging c'est pas hyper parlant pcq on a que le catalogue du ministère de la culture ...

Dès que j'ai votre :heavy_check_mark: je déploierai sur la prod (là où il y a plus de catalogues)

**Comment by DaFrenchFrog** [comment]
@Volubyl C'est ok pour moi sur ce que je vois sur staging.

**Comment by Volubyl** [comment]
Ok c'est en prod!



@DaFrenchFrog @johanricher si vous remarquez qqch d'étrange n'hésitez pas à me le dire.

Sinon, on va pouvoir fermer cette issue :-)

**Comment by DaFrenchFrog** [comment]
En prod il y a des problèmes d'alignement. Il faudrait que l'image reste "inclue" dans le rectangle défini (160x90) et que les images prennent toute la place disponible sans être déformées. 
<img width="580" alt="image" src="https://user-images.githubusercontent.com/25462034/210359811-d70178ba-3826-4e3d-a8bc-065b9514ae1a.png">

Dis-moi si tu as besoin de précisions.

**Comment by Volubyl** [comment]
non c'est clair ! Je corrige ça

**Comment by Volubyl** [comment]
@DaFrenchFrog ça me semble corrigé

**Comment by DaFrenchFrog** [comment]
C'est ok pour moi !

**Comment by Volubyl** [comment]
super je ferme l'issue alors!
