### ISSUE TITLE
Modules de schéma complémentaire

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#44]
# Problème & sources
Chaque organisation et service peut d'avoir des schémas différents, et un schéma standard unique serait trop limitatif pour combler l'ensemble des besoins.

Un schéma dit "complémentaire" est un ensemble de champs de saisie (textes, cases à cocher, menus déroulants,...) prédéfinis regroupés sous un même nom. Ces champs viennent en complément du schéma standard commun à tous les jeux de données. 

# Solution proposée
ETQ contributeur : A la manière d'un plugin, je peux sélectionner parmi une liste de schémas complémentaires celui qui répond à mon besoin afin d'y saisir de nouvelles informations.
ETQ réutilisateur : lors de la phase de recherche je peux sélectionner un schéma complémentaire et filtrer selon ses caractéristiques
ETQ admin : je peux créer des modules de schéma complémentaire afin qu'ils soient proposés aux contributeurs (dans un premier temps la création de nouveaux modules sera confiée aux équipes de développement pour une meilleure maitrise des doublons et plus simplicité)

# Forces
- Possibilités de compléter le schéma standard à volonté
- Gestion optimale des schémas

# Faiblesses
- Si les schéma sont gérés indépendamment par chaque organisation il peut y avoir des conflits potentiels lors d'une recherche multi-organisation. Il faudrait alors que ces schémas soient géré côté dev.

# Modules complémentaires vs catalogues
Une option qui pourrait être envisagée serait de ne pas avoir de module complémentaire mais plutôt de gérer un système de catalogues, qui intègreraient ces champs complémentaires. Ainsi, un jeu de données est ajouté à un catalogue (et non à une organisation) et chaque catalogue possède ses propres données complémentaires, qui auront été définies lors de sa création.

# Validation
A discuter avec les pilotes et à tester avec les utilisateurs finaux.

**Comment by johanricher** [comment]
J'ai besoin qu'on définisse ce qu'est un "module de schéma complémentaire".

**Comment by DaFrenchFrog** [comment]
@johanricher J'ai complété le ticket pour donner une définition plus précise et j'ai ajouté une option qui pourrait remplacer ce principe. Je vais créer un nouveau ticket exploration dans ce sens. Ce sujet devrait d'abord être discuté avec les pilotes avant d'être testé avec les utilisateurs.

**Comment by johanricher** [comment]
Si je comprends bien chaque organisation aurait plusieurs schémas pour un même catalogue, potentiellement autant de schémas qu'il y a de jeux de données ?

Je pense qu'il y a un asymétrie entre contributeur et réutilisateur, en termes de besoins et de connaissances (métiers, sur les jeux de données dans le catalogue). 

Il faut trouver un compromis entre ces deux points de vue, le contributeur qui aura tendance à exprimer l'envie de pouvoir décrire chaque jeu de données de façon fine et spécifique, et le réutilisateur qui n'aura pas forcément la même vision fine, métier, du jeu de données et verra plutôt des avantages que des inconvénients à ce que chaque jeu de données soit décrit de la même façon.

> ETQ réutilisateur : lors de la phase de recherche je peux sélectionner un schéma complémentaire et filtrer selon ses caractéristiques

Comment rendre cela compréhensible aux réutilisateurs qui n'ont justement pas la même expertise que les contributeurs ? Si chaque jeu de données a un schéma, est-ce qu'on ne va pas se retrouver avec un menu déroulant dans lequel on ne sait que choisir et qui le rend inutilisable (problème de découvrabilité d'un schéma parmi d'autres) ? Lors d'une recherche comment savoir par avance si un jeu de données que je cherche va correspondre à un schéma ? si oui lequel ?

> Gestion optimale des schémas

C'est à dire ?

**Comment by DaFrenchFrog** [comment]
> Si je comprends bien chaque organisation aurait plusieurs schémas pour un même catalogue, potentiellement autant de schémas qu'il y a de jeux de données ?

Non ce n'est pas ça. Et évidemment le but n'est pas d'avoir autant de schémas qu'il y a de jeux de données. Il faut déjà que l'on définisse précisément ce qu'est un catalogue et comment il s'articule autour d'une organisation. Si on considère que c'est le responsable de données qui décide des modules complémentaires, c'est lui qui décidera alors de créer ou non des complément si cela est nécessaire.

> Comment rendre cela compréhensible aux réutilisateurs qui n'ont justement pas la même expertise que les contributeurs ?

Le réutilisateur n'est en aucun cas obligé d'utiliser les critères d'un schéma complémentaire s'il ne les maitrise pas. Simplement dans les critères de recherche et suite à un premier affichage de résultaats on pourra sélectionner un module complémentaire parmi ceux disponibles (via un menu déroulant), et une fois sélectionné on affichera les champs concernés par ce dernier et on pourra jouer avec pour affiner sa recherche.

> Si chaque jeu de données a un schéma, est-ce qu'on ne va pas se retrouver avec un menu déroulant dans lequel on ne sait que choisir et qui le rend inutilisable (problème de découvrabilité d'un schéma parmi d'autres) ?

Chaque jeu de données a le schéma standard mais il n'a pas forcément un schéma complémentaire. C'est une option non obligatoire qui permet simplement plus de granularité sur un sujet donné. On pourrait aussi tout à fait envisager que les schémas complémentaires soient définis de façon collégiale et soient communs à tous les ministères. Ainsi, un schéma complémentaire "Inspire" (si tant est qu'il soit opportun) pourrait être utilisé de manière identique pour l'ensemble des organisation.

> Lors d'une recherche comment savoir par avance si un jeu de données que je cherche va correspondre à un schéma ?

C'est justement à ce que sert la recherche. Je tape un premier texte qui affiche un grand nombre de résultats, ensuite je sélectionne un schéma complémentaire qui m'affiche uniquement les jeux de données qui intègre ce schéma. 

Mais de toutes façons il reste encore à vérifier avec les responsables métier que le fait d'avoir des données supplémentaires est bien nécessaire. Il est encore trop tôt pour affirmer que ces modules sont une bonne idée. Je vais essayer de faire un graphique pour avoir une meilleure idée d'une telle implémentation.

**Comment by johanricher** [comment]
Super base de départ pour tester ces features :+1: Merci pour les diagrammes !

**Comment by johanricher** [comment]
> # Problème & sources
> Chaque organisation et service peut d'avoir des schémas différents, et un schéma standard unique serait trop limitatif pour combler l'ensemble des besoins.
> 
> Un schéma dit "complémentaire" est un ensemble de champs de saisie (textes, cases à cocher, menus déroulants,...) prédéfinis regroupés sous un même nom. Ces champs viennent en complément du schéma standard commun à tous les jeux de données. 

Pour résoudre ce problème, l'ajout de champs complémentaires sera possible à la création du catalogue. #284
