### ISSUE TITLE
Page vie privée

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#482]
Les mentions relatives à l’utilisation des données personnelles et à la gestion des cookies doivent être visibles sur le site.

Exemples :
* [api.gouv.fr](https://api.gouv.fr/vie-privee)
* [Annuaire des entreprises](https://annuaire-entreprises.data.gouv.fr/vie-privee)

## Tâches

* [x] @johanricher Ecrire contenu : https://pad.incubateur.net/aE48U2ZvSdmILJjE7T0aBQ
* [x] @florimondmanca Relire draft
* [ ] #496
  * Implémenter le contenu dans une nouvelle page `catalogue.data.gouv.fr/vie-privee`
  * Ajouter lien dans le footer

**Comment by johanricher** [comment]
Premier draft : https://pad.incubateur.net/aE48U2ZvSdmILJjE7T0aBQ

**Comment by florimondmanca** [comment]
> Ce site a été conçu de telle façon à réduire au minimum la collecte et le traitement des données à caractère personnel.

Je dirais "de façon à réduire la collecte" (tout court). En effet "Réduire au minimum" est un peu ambigu, on pourrait comprendre comme "on n'a pas trop réduit".

**Comment by johanricher** [comment]
> Je dirais "de façon à minimiser la collecte". En effet "Réduire au minimum" est un peu ambigu (...)

"Minimiser" signifie juste "réduire". On perd l'idée qu'on a réduit le plus possible. J'ai repris la formulation dans le RGPD concernant ce qu'on appelle communément le "privacy by design" ;

> le responsable du traitement devrait adopter des règles internes et mettre en œuvre des mesures qui respectent, en particulier, les principes de protection des données dès la conception et de protection des données par défaut. Ces mesures pourraient consister, entre autres, à **réduire à un minimum le traitement des données à caractère personnel** (...)

> Est-il utile de préciser ce qu'on ne collecte pas (...) ?

Non, pas nécessaire en effet. Pour l'instant ça permet peut-être entre nous d'expliciter et vérifier ce qu'on collecte ou pas. Vous confirmez la liste ? par exemple l'adresse email il me semble en fait qu'on la traite puisqu'on l'affiche dans le header en mode connecté. On en a pas besoin (envoi de mails) donc on ne devrait pas la traiter (récupérer, stocker, afficher) mais pour l'instant on la traite.

Mon point c'est qu'on doit faire la liste des données personnelles qu'on traite, notamment celles qu'on récupère depuis MCP.

Ok pour ta reformulation.

**Comment by florimondmanca** [comment]
Ah, "réduire **_à_** un minimum" c'est parfait :+1:

> Vous confirmez la liste ? par exemple l'adresse email il me semble en fait qu'on la traite puisqu'on l'affiche dans le header en mode connecté. On en a pas besoin (envoi de mails) donc on ne devrait pas la traiter (récupérer, stocker, afficher) mais pour l'instant on la traite.

Oui, on collecte l'email et elle est en fait essentielle puisqu'à ce jour elle sert d'identifiant et doit donc être unique.

Par contre on ne traite pas l'ID du Compte DataPass (on a notre propre ID en base).

À l'avenir, on devrait en effet cantonner l'usage d'un email au seul mécanisme d'authentification email/mdp ("legacy"), car en effet du point de vue de l'authentification DataPass, on n'en a pas besoin. On devrait ne récupérer qu'un ID et un "display name". Ça demanderait qq changements pas tout-à-fait triviaux. Hélas, voilà un point de dette technique.

**Comment by johanricher** [comment]
Ok merci d'avoir ouvert ce ticket, ça permet d'envisager de réduire encore un peu le volume de données personnelles qu'on traite.

> Par contre on ne traite pas d'ID Mon Compte Pro (on a notre propre ID en base et Mon Compte Pro ne l'expose pas dans son endpoint par défaut).

Comment on récupère depuis l'API MCP les données d'un user (SIRET, adresse email) si c'est pas à partir de son ID ? Autre façon de poser la question : on ne stocke pas pour chaque user un mapping entre ID catalogue.data.gouv.fr et ID MCP ?

**Comment by florimondmanca** [comment]
> Comment on récupère depuis l'API MCP les données d'un user (SIRET, adresse email) si c'est pas à partir de son ID ? 

C'est possible grâce au protocole OpenID Connect utilisé par MonComptePro. Dans ce protocole on demande des `scopes` (ici `openid, email`), l'utilisateur s'authentifie puis le serveur renvoie un `code` qui permet d'accéder à un endpoint `GET /userinfo`. C'est là que l'on récupère email et organisations.

Et donc non il n'y a pas de mapping. On stocke seulement un `Account` (comprenant email, role, api token) et une entrée dans la table `DataPassUser` qui sert à savoir que cet utilisateur s'est connecté avec MonComptePro (éventuellement au terme d'une sélection de l'orga, ou d'avoir demandé la création de son orga, etc - ce qu'on ne refait pas plusieurs fois).

**Comment by johanricher** [comment]
Ok c'est top, merci pour ces précisions. J'ai mis à jour le pad. A priori il est complet ?

**Comment by florimondmanca** [comment]
Oui, en tout cas ce qui y est écrit me semble correct !
