### ISSUE TITLE
Finalisation de la page d'accueil visiteur

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#487]
Suite aux discussions sur #459 et le travail de Johan et Romain 

La [maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2321%3A39720) pour la home page a été mise à jour, notamment avec:

* [ ] Mise à jour des textes
* [x] "MonComptePro" et pas "Mon Compte Pro" -- utiliser le logo SVG fourni au lieu d'une réalisation custom (cf [lignes directrices MonComptePro](https://apigouv.notion.site/Interface-guidelines-du-bouton-MonComptePro-d316a5c2532d499db9edc3e9d8309602)) #490
* [ ] Bouton-lien "Enregistrer son organisation", qui doit pointer vers `https://github.com/etalab/catalogage-donnees/wiki/Documentation-%C3%A0-destination-des-utilisateurs#comment-enregistrer-une-organisation-sur-cataloguedatagouvfr-`
* [ ] Un nouveau schéma SVG https://github.com/etalab/catalogage-donnees/issues/487#issuecomment-1273544108

Ce ticket consiste à mettre à jour l'implémentation.

**Comment by johanricher** [comment]
Il faut mettre à jour "datapass" -> "Mon Compte Pro"

**Comment by DaFrenchFrog** [comment]
Pardon c'était le mauvais fichier...
![schéma login](https://user-images.githubusercontent.com/25462034/194903723-23ed2221-332b-4e65-bbc0-fcc0965adb1c.svg)

**Comment by johanricher** [comment]
Note : Je remarque qu'ils ont pas l'air d'être tout à fait au clair encore sur la stylisation du nom du service : "Mon Compte Pro" vs "MonComptePro". :thinking: 

Néanmoins je suppose que le logo ne va pas changer, on le reprend dans notre visuel ?

![](https://moncomptepro.beta.gouv.fr/images/moncomptepro.svg)

**Comment by DaFrenchFrog** [comment]
Le schéma avec le logo.
![schéma login](https://user-images.githubusercontent.com/25462034/194910240-6c8845dd-a592-4434-899c-9eff450cddff.svg)

**Comment by johanricher** [comment]
Nickel :ok_hand:
