### ISSUE TITLE
Mots-clés en double

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#506]
### Description du problème

Sur catalogue.data.gouv.fr, pour le catalogue du MC, dans l'interface de recherche d'un jeu de données, le champ mots-clés affiche tous les mots-clés en double :

![image](https://user-images.githubusercontent.com/10212787/198898795-7327543d-8568-4b79-b881-bdb5812ba173.png)

### Analyse plus technique

Le problème semble venir du fait qu'effectivement certains mots-clés (`tag`)  sont en doublon dans la DB de prod

C'est ce que permet de voir la requète SQL  

```
SELECT id, name
FROM tag
WHERE name IN (SELECT   name
FROM     tag
GROUP BY name
HAVING   COUNT(name) > 1)

```

### Pourquoi ces doublons ?

TODO

#### Court terme

~~Supprimer à la main les tag en doublon de la DB~~

En fait non cette solution n'est pas envisageable pcq il y a plus de 100 doublons en DB.

Pour le contexte, un tag est représenté par un nom et un id.

Il est possible que deux tags ayant le même nom aient des id différents (au niveau DB ce sont deux tags différents)

Seulement,  il y a souvent un cas qu'on pourrait illustrer comme ceci

En DB, il y a le tag "tata" qui possède l'id 1234 mais il y aussi un autre tag "tata" qui possède l'id 456

Le jeu de donnée A utilise le tag "tata" ayant l'id 1234
Le jeu de donnée B utilise lui le tag "tata" ayant l'id 456

Supprimer le tag 1234 ne suffira pas. Il faut aussi mettre à jour le dataset pour que celui-ci n'utilise plus le tag avec l'id 1234 mais celui avec l'id 456.

Cette opération est fastidieuse et source d'erreur si faite à la main.

C'est pourquoi je suis partis sur un script python qui permet d'effectuer ce travail

### Moyen terme

Comprendre mieux d'où ça peut venir.

A l'heure actuelle, j'ai l'impression que le script d' [import de catalogue](https://github.com/etalab/catalogage-donnees/blob/master/tools/import_catalog.py) ne vérifie pas si un tag existe déja pour un dataset donné.

Cela veut dire que si on importe x fois le même jeu de donnée, les tags du jeu de donnée seront eux aussi créés x fois

**Comment by johanricher** [comment]
@Volubyl va essayer de reproduire ça en local afin de déterminer si c'est un bug et de mieux le qualifier

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog c'est bon il n'y a plus de tags en double en prod, en staging et sur demo.

C'était un poil fastidieux mais c'est bon :ok_hand:

**Comment by johanricher** [comment]
Merci !

Quelle en était l'origine ? ça pourrait se reproduire dans certaines conditions ?

**Comment by Volubyl** [comment]
Lors de l'import de catalogue, l'on ne vérifiait pas si un tag était déjà importé en base de donnée. Donc si deux catalogues ont un tag ayant le même nom, ils seront importés deux fois.
