### ISSUE TITLE
Manque les suggestions sur les champs complémentaires

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#507]
## Description du bug

Sur catalogue.data.gouv.fr on est sensés avoir en proposition les informations qui ont déjà été saisies.

## Comportement attendu

Sur les champs libres complémentaires on devait avoir la liste des saisies précédentes des autres fiches pour ce champ.

**Comment by florimondmanca** [comment]
À ce stade ce n'est pas un "bug" mais une fonctionnalité à implémenter.

Hélas #405 n'avait pas été détaillé donc j'imagine qu'au moment de l'implémentation des champs complémentaires dans la fiche, on n'avait pas parlé d'une fonctionnalité d'auto-suggestion comme d'un critère bloquant pour la "livraison".

**Comment by johanricher** [comment]
Ce n'est pas clair dans la description du ticket mais je suppose qu'il est question du formulaire de création ou de modification d'une fiche (page `/contribuer`) et du comportement attendu sur les champs complémentaires de type "string" (chaine de caractère) en particulier. En l'occurence j'appelle le comportement que tu décris "autocomplétion".

Pour certains champs de type "string", comme le nom ou la description du jeu de données, le comportement attendu n'est pas l'autocomplétion car ça ne serait pas pertinent (tous les nom et toutes les descriptions sont uniques, par définition).

Pour les champs du "schéma commun", ça avait été discuté champ par champ. Par exemple pour le champ "Couverture géographique" qui est aussi de type "string", on avait implémenté l'autocomplétion (de telle façon à ce que soit affiché une liste de valeurs présentes en base, c'est à dire toutes les contributions sur ce champ faites sur les autres fiches).

Pour les champs dits "complémentaires", puisqu'on est obligé d'appliquer une même implé pour tous les champs, on l'a implémenté sans l'option autocomplétion.
