### ISSUE TITLE
ETQ qu'admin d'organisation je ne peux pas supprimer de fiche catalogue

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#508]
## Description du bug

Il n'y a pas de bouton permettant de supprimer une fiche lorsque je suis responsable de données.

## Comportement attendu

Avoir un bouton qui permet de supprimer des données.

**Comment by florimondmanca** [comment]
Je viens de vérifier, et c'est lié au fait que Roselyne Aliacar n'avait pas le rôle `ADMIN`.

En effet lorsqu'un utilisateur se connecte pour la première fois avec MonComptePro, le rôle est forcément un "USER" standard, il faut configurer le rôle ADMIN dans la DB.

@DaFrenchFrog Je viens de faire la manip, normalement RA devrait pouvoir supprimer des jeux de données désormais, elle peut réessayer. Qui faut-il ajouter d'autre ? (@Volubyl Je m'en occupe puisque j'avais la charge de #220.)

**Comment by johanricher** [comment]
Bien vu, on en avait parlé mais j'avais oublié qu'on devait le faire. :+1:
