### ISSUE TITLE
Le clic sur "Contacter le producteur" ouvre un mail sans destinataire

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#513]
## Description du bug

Testé sur Chrome et Firefox. Lors du clic sur le bouton contacter le producteur. Je n'ai aucun destinataire (voire j'ai null, selon le client mail utilisé). Alors qu'un contact est présent dans la fiche

![image](https://user-images.githubusercontent.com/10212787/198982980-840a68fd-6c2d-45b0-af20-d1e34971dd1a.png)

## Comportement attendu

Je dois avoir en destinataire l'ensemble des contacts saisis (perso + de service).

## Comportement réel

Un mail s'ouvre sans destinataire.

## Pour reproduire

- Se connecter
- Ouvrir une fiche catalogue (n'importe laquelle : [exemple](https://catalogue.data.gouv.fr/fiches/e4786090-c9d6-43d0-b87b-ca74f418c568))
- Cliquer sur contacter le producteur.

## Contexte supplémentaire

Si aucun contact n'est disponible alors il faudrait désactiver le bouton (disabled).

**Comment by johanricher** [comment]
Est-ce que tu peux mettre un lien vers la fiche ?

**Comment by DaFrenchFrog** [comment]
J'ai mis à jour le ticket avec un exemple mais ça le fait sur toutes les fiches (en tout toutes celles que j'ai testé).

**Comment by johanricher** [comment]
Entendu, merci ! Du coup c'est un doublon de #420

**Comment by Volubyl** [comment]
fermé car doublon de #420
