### ISSUE TITLE
ETQ personne/service ayant accès à l'export de catalogue, je ne peux voir que les jeux de données à la visibilité non restreinte

### ISSUE THREAD

**Issue by Volubyl** [etalab/catalogage-donnees#528]
**Métadonnées:**

rel : #298

Maquette : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2373%3A37961

# Description du besoin

Actuellement, il est possible de récupérer un export CSV en allant sur une url du type : `api/catalogs/:siret/export.csv`

Cet export est accessible à tout le monde et contient tous les jeux de données de tous les catalogues

Il faudrait pouvoir exporter que les jeux de données ayant une visibilité non restreinte (jeux de données public)

## Règle métier

- aucun jeu de donné ayant une visibilité restreinte ne doit figurer dans l'export csv

### Terminologie

Un jeu de donné ayant une *visibilité restreinte* est un jeu de donné dont un contributeur a choisi de NE PAS diffusé en open data. De ce fait, il ne sera visible que par les membres de l'organisation du contributeur 

# Analyse technique

### Analyse de l'existant

Pour le moment, rien en DB ne permet de déterminer si une fiche est visible ou pas.

##### Base de donnée

Une idée serait de trouver un moyen de pouvoir indiquer pour quelle organisation ce jeu est visible.

On pourrait par exemple ajouter à la table `dataset` une propriété de type ENUM `publication_restriction_reason`

Cette ENUM aura cette forma

```

class PublicationRestriction(enum.Enum):
    NONE = "none"  // the dataset has no publication restriction
    DRAFT = "draft"  // the dataset is a draft
	LEGAL_RESTRICTION = "legal_restriction" // the dataset is not published for legal reason
```

###### Création d'un jeu de donnée

Il va être nécessaire de rajouter une propriété `publication_restriction_reason` à l'API POST `/datasets`

Si la valeur de cette propriété est différente de `NONE`  cela veut dire que ce jeu de donnée sera visible uniquement aux personnes membres de l'organisation à l'origine de la création de ces jeux de donnée ET que ce jeu de donnée ne fera pas partie de l'export
 
 ###### Mise à jour d'un jeu de donnée

Il va être nécessaire de rajouter une propriété `publication_restriction_reason` à l'API PUT `/datasets`

Si la valeur de cette propriété est différente de `NONE`  cela veut dire que ce jeu de donnée sera visible uniquement aux personnes membres de l'organisation à l'origine de la création de ces jeux de donnée ET que ce jeu de donnée ne fera pas partie de l'export
 

#### Frontend

Sur le formulaire de contribution l'on pourra utiliser le composant du DSFR [Bouton radion riche](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/boutons-radio-riches)

Si l'utilisateur sélectionne "OUI" (pour restreindre la visibilité) une modale s'ouvrira

Pour cette modale l'on peut utiliser le composant [Generic Modal](https://github.com/etalab/catalogage-donnees/blob/master/client/src/lib/components/GenericModal/GenericModal.svelte)

Il va falloir rajouter un enum du type

```
export const DATASET_PUBLICATION_RESTRICTION: { [K in DataFormat]: string } = {
    NONE = "none"  // the dataset has no publication restriction
    DRAFT = "draft"  // the dataset is a draft
	LEGAL_RESTRICTION = "legal_restriction" // the dataset is not published for legal reason
```

### Exporter que les jeux de données n'ayant pas de restriction de publication

Ici l'objectif est de n'exporter dans le fichier d'export CSV que les jeux de données ayant la propriété `publication_restriction_reason` ayant la valeur `NONE` (pas de restriction de publication)

##### Récupération en DB

La requête SQL sera du type : 

```
SELECT *
FROM datasets
WHERE organisation.sire = <ORGANISAZATION_SIRET>
AND WHERE publication_restriction_reason IS NONE
```

La modification principale doit être faite du handler [GetAllDatasets](server/application/datasets/handlers.py)

On pourrait modfier la classe DatasetSpec pour pouvoir rajouter un filte 

```
class DatasetSpec:
    search_term: Optional[str] = None
    organization_siret: Optional[Siret] = None
    geographical_coverage__in: Optional[Sequence[str]] = None
    service__in: Optional[Sequence[str]] = None
    format__in: Optional[Sequence[DataFormat]] = None
    technical_source__in: Optional[Sequence[str]] = None
    tag__id__in: Optional[Sequence[ID]] = None
    license: Optional[str] = None
	publication_restriction: Optional[Sequence[PublicationRestriction]]
```

#### Modification du test d'API

Il faudrait écrire un test pour pouvoir vérfier qu"un export ne comprend pas de jeu de donnée ayant une restristriction de publication

## Critère d'acceptation

- [ ] L'export CSV ne comprend pas de jeu de donnée ayant une retriction de publication

**Comment by Volubyl** [comment]
@johanricher dans le ticket #289 tu as écrit que les jeux de données "restreints" sont visibles que pour les personnes membre de l'organisation.

Pour l'export, je n'ai pas moyen de savoir qui a rentrée l'url pour accéder à l'export et donc je suis dans l'incapacité de savoir de quelle organisation cette personne fait partie.

Dans ce cas là, ma propal serait de ne pas inclure dans l'export les jeux de données ayant une visibilité restreinte.

Tu en penses quoi ?

**Comment by johanricher** [comment]
> ne pas inclure dans l'export les jeux de données ayant une visibilité restreinte

Oui c'est exactement ça le critère d'acceptation. :+1:  (désolé je n'avais pas vu cette question !)
