### ISSUE TITLE
Ouvrir les liens dans un nouvel onglet

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#532]
## Description

Sur la page du formulaire de contribution (https://catalogue.data.gouv.fr/contribuer), certains liens présents sur la page s'ouvrent dans l'onglet en cours et font perdre à l'utilisateur les informations saisies (tant que #531 n'est pas implémenté).

Actuellement le problème se pose avec les liens présents dans la description des champs complémentaires du ministère de la Culture.

## Critères d'acceptation

* Tous les liens de cette page doivent s'ouvrir dans un nouvel onglet, y compris pour les champs complémentaires des futurs catalogues.

**Comment by Volubyl** [comment]
@johanricher c'est bon c'est sur staging

**Comment by Volubyl** [comment]
Pour info et mémoire, réponse reçue à propos des bonnes pratiques en matière de lien avec "target=_blank"

chez Démarches Simplifiées on a récemment itéré sur ce sujet suite à des recommandations pour améliorer notre accessibilité justement. Pour résumer on applique les règles suivantes :

les liens externes s'ouvrent dans un nouvel onglet avec target="_blank"
le DSFR rajoute l'icône conventionnelle à droite du lien
l'attribut title mentionne en suffixe " - Nouvel onglet". (C'est aussi une info pertinente indépendamment de l'accessibilité donc ce n'est pas un aria-label)
on rajoute l' attribut rel="noopener noreferrer". Ce n'est pas en lien avec l'accessibilité, mais une mesure de sécurité et confidentialité
De notre expérience, comme ça touche aussi à l'UX, que cela affecte tous les utilisateurs, qu'il y a des habitudes bien ancrées qui dépendent aussi des réglages du navigateur, c'est difficile de tout concilier. Mais pour le moment ça semble bien marcher

**Comment by johanricher** [comment]
Nickel  :+1: bien joué ! :clap:
