### ISSUE TITLE
Améliorer page d'accueil hors connexion

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#545]
## Description

Ce ticket mélange plusieurs améliorations concernant la page d'accueil

* Mettre à jour le bouton MCP avec les [nouvelles spécifications visuelles](https://github.com/betagouv/moncomptepro#sp%C3%A9cifications-visuelles)
* Mettre à jour la liste des [organisations](https://github.com/etalab/catalogage-donnees-config/tree/main/organizations) (ajout DINUM, MEAE, ANAH)
* Petits tweaks du parcours

Sur ce dernier point, qui est apparu suite aux différents tests, voici ma proposition :

Actuellement, la home est divisée en 3 sections (en dessous du header) : 1. bannière avec fond lavande, 2. Diagramme explicatif, 3. Liste des organisations

* Dans la bannière : enlever "Votre organisation doit être enregistrée pour vous identifier." et le bouton "Enregistrer mon organisation", on ne garde que le bouton MCP qu'on met au centre. Le but est que les utilisateurs cliqnent sur le bouton sans se poser trop de questions.
* Inverser l'ordre des 2 sections suivantes : d'abord mettre la liste des organisations et changer le titre en "Organisations enregistrées".
* Ensuite mettre le diagramme et en dernier on met le bouton "Enregistrer mon organisation".

Ainsi le parcours me paraît suivre une logique plus en accord avec ce que j'ai retenu des tests : les utilisateurs passent trop de temps avant de cliquer sur le bouton MCP. Si leur organisation n'est pas enregistrée, ils verront de toute façon le message d'erreur de catalogue.data.gouv.fr et seront renvoyés sur la page d'accueil où ils pourront trouver les informations complémentaires.

## Prochaines étapes 

* On affine le parcours pour mettre à jour la maquette de la page d'accueil
* Implémentation de la nouvelle maquette

**Comment by DaFrenchFrog** [comment]
Voici une première proposition pour la page d'accueil (maquette Figma [ici](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2385%3A61939&t=3B9sotal3DvSGu9B-1)) : 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/25462034/212730785-86b834b5-58e1-4c48-91cf-0e442c32a3a4.png">

J'ai suivi ta recommandation à part pour le bouton "Enregistrer son organisation".Je pense qu'il vaut quand même mieux avoir ce bouton au même endroit que la liste des organisation. C'est plus cohérent en terme de hiérarchisation de l'information.

Qu'en pensez-vous ?

**Comment by johanricher** [comment]
Il faut ajouter l'ANAH : https://github.com/etalab/catalogage-donnees-config/tree/main/organizations/anah

**Comment by johanricher** [comment]
On décide aujourd'hui : intégrer les logos dans des cards ce qui permet de mieux les distinguer.

Valider le bon logo DINUM.

**Comment by DaFrenchFrog** [comment]
@Volubyl @johanricher J'ai mis à jour la page non connectée avec les cartes du Design System (elles sont un peu grandes mais il n'y a pas plus petit...)

[Maquette ici](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2385%3A61939&t=klXvPjz1KhD0kql7-1)

**Comment by Volubyl** [comment]
ok je me lance là dedans.

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog ça aussi c'est sur staging.

Mais quelle journée dites donc !

**Comment by johanricher** [comment]
Merci ! Je vois quelques petits peaufinages car je suis maniaque :

* Enlever "Votre organisation doit être enregistrée pour vous identifier."
* Mauvais logo pour la DINUM
* "Organisation enregistrée" au lieu de "En cours"

Petites corrections supplémentaires par rapport à la maquette (que je ne peux pas modifier) :

* "Agence nationale de l'habitat" au lieu de "Anah" 
* "Direction interministérielle du numérique" au lieu de "DINUM"
* Pas de majuscule au "étrangères" de "Ministère de l'Europe et des Affaires étrangères" (emoji maitre Capello :nerd_face:)
* Classer les organisations par ordre alphabétique au sein de chaque catégorie ("Catalogue activé" puis "Organisation enregistrée")

**Comment by Volubyl** [comment]
@johanricher c'est sur staging

**Comment by johanricher** [comment]
C'est parfait ! LGTM :pray:
