### ISSUE TITLE
Gérer les logos larges

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#553]
## Description

Quand le logo d'une organisation a un ratio important (image trop large), il empiète sur le texte à droite (nom du jeu de données, nom du producteur, mots-clés).

Exemple sur cette fiche : https://catalogue.data.gouv.fr/fiches/eca096c7-d7b8-4a74-8d23-0154dcb18124

![image](https://user-images.githubusercontent.com/10212787/214279892-01206544-539c-4e36-97a4-fe538075ecf5.png)

Je vois 2 options de solution : 
1. Contraindre la largeur de l'image
2. Contraindre la hauteur de l'image et adapter dynamiquement le placement du texte à droite de l'image

## Tâches

On opte pour l'option 1, comme pour l'affichage des logos dans la page des résultats de recherche.

**Comment by DaFrenchFrog** [comment]
Il faut utiliser le même principe que celui qui a été implémenté pour les items de recherche. C'est le fonctionnement qui a été implémenté ici :  https://github.com/etalab/catalogage-donnees/issues/434#issuecomment-1369737387

**Comment by johanricher** [comment]
Donc l'option 1, avec comme inconvénient que le logo sera peu lisible. On encourage les organisations à fournir un logo avec un ratio faible (plus "carré"). :+1:

**Comment by DaFrenchFrog** [comment]
@johanricher Le ratio que j'utilise dans les maquettes est un ratio 16:9. Après on peut décider de le changer pour un carré ou bien agrandir la zone dans les mêmes proportions.
