### ISSUE TITLE
Laisser ouvert le menu Affiner la recherche lors d'une recherche

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#560]
# Description

Lorsqu'une recherche est en cours, c'est à dire que l'URL `https://catalogue.data.gouv.fr/fiches/search` est suivie de paramètres de recherche (autres que `q=` seul pour une recherche simple, plein texte), le menu Affiner la recherche est fermé au chargement de la page, par exemple lors d'un raffrachissement de la page ou de l'ouverture de la page à partir un lien.

Le menu Affiner la recherche devrait rester ouvert lorsqu'une requête de recherche est en cours.

**Comment by Volubyl** [comment]
@johanricher c'est sur staging

**Comment by johanricher** [comment]
C'est parfait
