### ISSUE TITLE
Métadonnées simples dans la fiche de données

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#58]
Refs #19 

_(Cette issue est une exploration de ma part. Elle est probablement vouée à être redécoupée !)_

Parmi les métadonnées associées à un dataset, ajouter celles qui sont "simples", c'est-à-dire des données "statiques" non liées à une autre entité dans la BDD

## Métadonnées visées ?

En se basant sur la maquette : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE?node-id=236%3A513

On a donc en l'état :

Informations :

- `format` - _(str)_ Format de données _[(?) - À préciser / confirmer]_
- `geographical_coverage` - _(str)_ Couverture géographique - Enum ? Texte libre + thesaurus ?
- `time_coverage` - _(?)_ Couverture temporelle, de quand à quand le jeu de données est valide

Gouvernance :

- `producer_name` - _(str)_ Nom du service producteur de la donnée _[Texte libre, dans un premier temps]_
- `first_published` - _(date, Optionnel)_ Date de première publication
- `update_frequency` - _(date, Optionnel)_ Fréquence de mise à jour
- `last_updated` - _(date, Optionnel)_ Date de dernière mise à jour connue

Ouverture :

- `visibility` - _(`open | shared | internal`)_ Visibilité du jeu de données. Codes : `open` =
-  disponible en open data, `shared` = visible par les autres organisations, `internal` = visible par mon organisation uniquement
- `license` - _(str)_ Licence d'utilisation, si `open`
- `file_url` - _(str, optionnel)_ Lien du fichier de données, si `open`
- `preview_url` - _(str, optionnel)_ Lien de visualisation, si `open`
- `closed_reason` - _(str, Optionnel)_ Raison pour laquelle le jeu de données ne peut pas être mis à dispo du public (`visibility != open`). Stockage sous la forme de texte libre (permettant une valeur "Autre") + thesaurus (value-label, permettant des options connues, avec un lookup de la value à l'affichage pour le label correspondant)

## Pour plus tard ?

Les "métadonnées complexes" (pour plus tard) sont :

- Contacts
- Tags
- Producteur de la donnée (_lié à l'organisation courante_)

**Comment by DaFrenchFrog** [comment]
@florimondmanca il faudrait également ajouter la couverture temporelle (j'ai mis à jour la maquette) :
https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE?node-id=236%3A513

**Comment by florimondmanca** [comment]
Je vais fermer ceci, c'était intéressant comme listing mais concrètement on ne va pas se servir de ce macro-listing pour en faire des tickets / PRs et avancer. J'ai ouvert par ex #76 pour le champ "Format de données" que j'ai lié sur le ticket #19. On pourra faire ça au fur et à mesure pour les autres champs.
