### ISSUE TITLE
Accueil non connecté : Bouton "FranceConnect" au lieu de "MonComptePro"

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#581]
## Description du bug

Le bouton de connexion sur la page d'accueil n'est pas le bon. L'intitulé doit être "MonComptePro" et pas "FranceConnect".

Le bouton à utiliser est ici : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2385%3A61939&t=YzxwKUZZCw4zKwNz-1

<img width="283" alt="image" src="https://user-images.githubusercontent.com/25462034/224775347-b4c1de2c-69ba-4c86-b751-bc4a6b35841e.png">

## Contexte supplémentaire

@johanricher je te laisse compléter si nécessaire.

**Comment by johanricher** [comment]
Bien vu ! il y a sûrement eu un changement côté MCP qui s'est répercuté automatiquement chez nous. :thinking:
