### ISSUE TITLE
Mettre à jour organisations sur la page d'accueil hors connexion

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#587]
Sur la page d'accueil hors connexion 2 organisations, l'ANAH et la DINUM, sont indiquées comme étant "enregistrées" ce qui veut dire que leur catalogue n'est pas activé.

La DITP a été ajoutée.

Toutes les organisations sont actuellement [configurées](https://github.com/etalab/catalogage-donnees-config/tree/main/organizations/) avec un schéma de catalogue.

## Tâches

Mettre à jour la page d'accueil pour que les organisations aient comme statut "Catalogue activé" 
* ANAH
* DINUM
* DITP

**Comment by Volubyl** [comment]
@johanricher je pense qu'on peut fermer cette issue non ?

**Comment by johanricher** [comment]
En effet ! ça a été traité

* https://github.com/etalab/catalogage-donnees-config/pull/37
* https://github.com/etalab/catalogage-donnees/pull/595
