### ISSUE TITLE
Ajouter des tests pour le mobile

### ISSUE THREAD

**Issue by magopian** [etalab/catalogage-donnees#62]
Sous deux formes possibles :
- faire tourner les tests playwright [aussi sur mobile](https://playwright.dev/docs/test-configuration#emulation)
- écrire des [tests spécifiques pour mobile](https://playwright.dev/docs/emulation) (par exemple pour le menu hamburger, l'affichage du fil d'Ariane)

**Comment by florimondmanca** [comment]
Je ferme car finalement on ne met pas de focus particulier sur le mobile, bien qu'il faille y faire attention sur les pages publics (visiteurs lambda). L'hypothèse est que nos utilisateurs (agents) seront sur poste PC.
