### ISSUE TITLE
ETQ utilisateur je peux chercher un jeu de données

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#66]
## User Story

En tant qu'utilisateur,  
je souhaite chercher un jeu de données dans le catalogue de mon organisation,  
afin d'accéder aux informations le concernant.

## Parcours

* Je me connecte à l'outil avec mon compte utilisateur #12 
* Depuis la page d'accueil, un champ de recherche est présent
* Depuis n'importe quelle page de l'outil, je clique sur un bouton "Rechercher" qui m'amène à une page dédiée
* Dans le champ de recherche je peux saisir un texte de mon choix
* Lorsque je clique sur "Rechercher" ou j'appuie sur la touche d'entrée, le résultat s'affiche en dessous du champ (dans la page dédiée si j'ai fait ma recherche depuis la page d'accueil)

## Design

Voir [maquette page d'accueil](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE?node-id=431%3A11368)

## Critères d'acceptations

* [x] Must have (MVP) : simple recherche plein texte
* [ ] Should have (MVP ou plus tard) : fonctions de recherche avancées (tri, filtre, facettes...)

## Implémentation

- [x] #94
- [ ] #103

**Comment by florimondmanca** [comment]
@johanricher Je me demande quels champs la requête "plein texte" devrait viser. Pour l'instant je pense à :

* Titre
* Description

**Comment by johanricher** [comment]
Oui avec les schémas qu'on a pour l'instant (si je me réfère à [ce fichier](https://github.com/etalab/catalogage-donnees/blob/915da674571edfa160eb87a51f045dbd99c0aa4d/server/api/datasets/schemas.py)). Plus tard, il faudra y ajouter le champ `mots_cles` et peut-être d'autres.

**Comment by johanricher** [comment]
Parcours MVP complet, sera amélioré notamment avec #103 (recherche plein texte) et #126 (recherche structurée).
