### ISSUE TITLE
Instance de démo

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#67]
**Problème**

Pour les besoins de la "demo" dans le cadre du MVP, on va avoir besoin de permettre à des personnes d'effectuer des tests ou prendre en main l'outil en vue de faire des retours. Même s'il sera clair que l'espace qui leur sera dédié sera "instable" (pas de garantie de sauvegarde de données, etc), il faut qu'il soit séparé et précisément contrôlé.

**Solution proposée**

Une instance ("serveur") séparée pour accueillir un espace de demo, séparé de staging

**Pistes d'implémentation**

- Obtenir une instance "demo" chez Scaleway : configurer une VM et une DB (voir #25)
- Y déployer l'outil grâce au setup Ansible

Pour la suite (considérations "sec" / "ops" / etc devant s'appliquer aussi à staging ?) :

- Configurer un nom de domaine, par ex sur demo.catalogue.multi.coop
- Configurer TLS (via LetsEncrypt)

**Comment by johanricher** [comment]
Dans un premier temps, l'instance sera déployée sur `demo.catalogue.multi.coop`.

**Comment by florimondmanca** [comment]
@johanricher 

La première étape semble de se procurer une deuxième instance chez Scaleway

Je reprends les specs de https://github.com/etalab/catalogage-donnees/issues/25#issuecomment-1014779251 :

    AZ : Paris 2
    Instance : DEV-S
    Image : Debian Bullseye
    Stockage : 20 GB
    Nom : catalogage-demo

Pourrais-tu la créer stp ? Ma clé SSH est la 2e [ici](https://github.com/florimondmanca.keys).

Pour la DB j'envisage à ce stade de réutiliser la DEV-S-DB qu'on a déjà en y ajoutant une database (`rdb-demo`). Je viens de vérifier et j'ai les droits pour le faire en me connectant à la DB avec `psql`. Pour l'instant ça devrait suffire.

**Comment by florimondmanca** [comment]
J'ai merge #128, on a ce qu'il faut pour déployer sur cette instance séparée : http://51.159.133.202

Je vais mettre la config noms de domaine / TLS dans un ticket séparé.
