### ISSUE TITLE
Mettre en cache le navigateur playwright de manière plus fine

### ISSUE THREAD

**Issue by magopian** [etalab/catalogage-donnees#69]
Refs https://github.com/etalab/catalogage-donnees/pull/61#discussion_r802917573

À l'heure actuelle à chaque fois qu'on modifie une dépendance javascript le navigateur playwright (`npx playwright install firefox`) va être réinstallé, parce que la clé de cache qu'on utilise est le `package-lock.json`.

Il serait préférable de le faire dans cet ordre dans le CI :
- installer les dépendances javascript (y compris playwright donc)
- mettre en cache le navigateur playwright avec la clé `npx playwright --version`
- installer le navigateur playwright `npx playwright install firefox`

Il faut faire attention à ne pas dégrader l'expérience utilisateur : 
- on ne veut pas que le navigateur playwright soit lancé à chaque lancement des tests e2e en local
- bien documenter si il faut une étape supplémentaire en locale avant de pouvoir lancer les tests e2e (si l'installation n'est plus faite automatiquement lors du `make install`)

**Comment by florimondmanca** [comment]
À l'usage, je n'ai pas l'impression que ce ticket (qui ne concerne que la CI) puisse / doive être traité. Je vais le fermer.
