### ISSUE TITLE
Retirer les breadrcumbs (fil d'Ariane)

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#84]
cc @DaFrenchFrog @magopian 

Lors du dev nous avons ajouté un "fil d'Ariane" (en anglais : breadcrumbs), voir [#54](https://github.com/etalab/catalogage-donnees/pull/54/files#diff-debdec89126b81d078511329d30eb3d87398eefae4a22138fde56e8705bf5484)  mais ceci n'est pas présent dans les maquettes.

Actuellement il fait en effet doublon avec le reste de la navigation (Rechercher / Contribuer / Mon espace), et il faudrait probablement réfléchir plus amplement à la navigation.

Je propose donc de les retirer pour l'instant.

**Comment by DaFrenchFrog** [comment]
OK. A ma connaissance le fil d'ariane est surtout utile dans dans deux cas :
- Lorsque la navigation a plusieurs niveaux de profondeur (ce qui est de moins en moins une bonne pratique)
- Le référencement naturel

Pour l'instant il n'est donc effectivement pas utile.
